### ISSUE TITLE
Better way to manage js/css dependencies

### ISSUE THREAD

**Issue by xiaohanyu** [quokkaproject/quokka#103]
Seems quokka depends on lots of external js library, such as
- bootstrap
- lepture/editor
- tinymce

So I'm considering a better way to organize and manage the js dependencies. 

These days I'm trying to learn something about nodejs, and some js dependency managment project such as https://github.com/component/component. 

So if you think this is the right choice, I can provide some help.

**Comment by rochacbruno** [comment]
Any help is very appreciated in the front-end features.

[Flask Assets](http://elsdoerfer.name/docs/flask-assets/) is already on requirements, but I dont know if that helps on this issue.

As I am not versed on the front-end development tools, feel free to propose/provide a solution.

**Comment by gianpaj** [comment]
http://bower.io/ is very easy to use

**Comment by rochacbruno** [comment]
found this https://github.com/tav/assetgen

**Comment by rochacbruno** [comment]
this http://thomassileo.com/blog/2013/12/12/using-yeoman-with-flask/

**Comment by rochacbruno** [comment]
should be nice to have this along with #231
