### ISSUE TITLE
Questions about themes

### ISSUE THREAD

**Issue by xiaohanyu** [quokkaproject/quokka#104]
I have some questions about quokka themes:
1. Seems you have forked flask-theme2 to a new project quokka-themes, could you explain why?
2. I didn't figure out a way to change the theme for portal list in index page from "default" theme to other. 
3. Why separate theme design for portal page and admin page?

Thanks.

**Comment by rochacbruno** [comment]
1. I made some changes to Flask-Admin, now it is possible to pass a list of themes to try and also a list of template files, that is the reason for the fork.
2. You can change the theme in admin -> settings or in local_settings.py file, the key is DEFAULT_THEME and ADMIN_THEME
3. Flask-Admin is a separate application, ir uses bootstrap 2.x, the default theme uses bootstrap 3.x, so it needed to be separate themes to avoid conflict with static files.

**Comment by xiaohanyu** [comment]
Hi, I've tried your method but it doesn't work for me to change a theme. 

And I've found the locate the problem in the following code: 

``` python
# coding: utf-8

from quokka_themes import Themes


def configure(app, db=None):
    themes = Themes()
    themes.init_themes(app, app_identifier="quokka")

    try:
        from quokka.core.models import Config
        s = Config.objects.get(group='settings')
        settings = {i.name: i.value for i in s.values}
        app.config.update(settings)
    except Exception as e:
        print(str(e))
```

the `app.config.update(settings)` will change the theme back to `default` and `cosmo`. Weird.

**Comment by rochacbruno** [comment]
Ok, I ve got it! I will fix it!

By The way, you can set it on admin instead of local_settings.

admin > settings > Config > settings (http://awesomescreenshot.com/0e821kctf7)

change the keys there.

I will fix that problem soon. Just have to check if there is already a THEME set on settings file before updating.

Tks.

**Comment by xiaohanyu** [comment]
Great! Thanks. 

I'm trying to read the source code of quokka, but still not understand all. Maybe I can provide some pydoc as I read the code for functions and classes in order to have a deep understanding of this project.

**Comment by rochacbruno** [comment]
It would be nice if you include docstrings in classe/functions, so we can generate dev documentation in the future.
