### ISSUE TITLE
Move babel script to makefile or manage.py 

### ISSUE THREAD

**Issue by xiaohanyu** [quokkaproject/quokka#106]
Hi, I think there maybe better ways to do babel i18n things. 

My idea is to move the `babel.sh` or `babel.bat` file to `manage.py` or `Makefile`. 

`Makefile` is a little easier, while `manage.py` is more portable. 

Which way do you prefer, @ellisonleao ?

Or do you think this is better than original?

If you approve, I'll provide some help for migrating.

Thanks.

**Comment by xiaohanyu** [comment]
Hi, I've made some work on this topic, do you think it is proper?

**Comment by rochacbruno** [comment]
Your call @xiaohanyu, as I never used the babel before (actually you are the first one using this), so you can define the best way for this to work.

I think manage.py will be better than make, but you decide.

**Comment by xiaohanyu** [comment]
Sure, OK. I'll make a pull request, then. I've also found this problem: https://github.com/pythonhub/quokka/issues/109, trying to fix it now.
