### ISSUE TITLE
Add captcha in user register form,

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#112]
user register form needs optinoal captcha

**Comment by rochacbruno** [comment]
we really need this along with #235

**Comment by rochacbruno** [comment]
https://github.com/mardix/flask-recaptcha

**Comment by rochacbruno** [comment]
@realli we should add a Recaptcha on that register form to avoid spammers. Now it will be possible with your latest PR. :+1:

**Comment by rochacbruno** [comment]
http://stackoverflow.com/a/19546264

**Comment by rochacbruno** [comment]
example: https://github.com/lepture/flask-wtf/tree/master/examples/recaptcha

**Comment by realli** [comment]
we have to figure out how to make flask recaptcha work with flask security

**Comment by rochacbruno** [comment]
I guess we don't need Flask Recaptcha @realli since wtf has built in Recaptcha field.

**Comment by realli** [comment]
@rochacbruno you are right, I can try that

**Comment by felipevolpone** [comment]
It's been developed in the doing_112 branch.

**Comment by rochacbruno** [comment]
@felipevolpone  look this commit https://github.com/quokkaproject/quokka/commit/4669e7ea9b3a399ad1c39c955317c92d4a9d1f24

in this file https://github.com/quokkaproject/quokka/blob/4669e7ea9b3a399ad1c39c955317c92d4a9d1f24/quokka/ext/security.py

ther is the ExtendedRegisterForm, than captcha should be added to that form, I guess we dont need to create new views as we can customize the flasksecurity forms
