### ISSUE TITLE
Quickstart states wrong port.

### ISSUE THREAD

**Issue by cldershem** [quokkaproject/quokka#118]
Quickstart says the following:
    1. Run
    $ python manage.py runserver
    Access on http://localhost:8000
    Admin on http://localhost:8000/admin

However, the application seems to only be accessible on port 5000.

Suggested fix, update Quickstart.

**Comment by ellisonleao** [comment]
just a reminder @cidershem , if you want to use 8000, you can start by typing 

```
./manage.py run0
```
