### ISSUE TITLE
UndefinedError: 'None' has no attribute 'is_authenticated'

### ISSUE THREAD

**Issue by imgxx** [quokkaproject/quokka#119]
File "/home/img/quokka/quokka/themes/default/templates/base.html", line 89, in block "access_control"
{% if current_user.is_authenticated() %}

Ubuntu 13.04, python 2.7 
Quokka installed as in quick start with populate and example local_settings

**Comment by rochacbruno** [comment]
That problem is an issue with Flask-Login, https://github.com/maxcountryman/flask-login/issues/135

**Comment by rochacbruno** [comment]
I fixed the version of Flask-Login to 0.2.6 as 0.2.8 breaked compatibility with Flask-Security.
