### ISSUE TITLE
Replicaset?

### ISSUE THREAD

**Issue by rturk** [quokkaproject/quokka#123]
Is mongodb replicaset supported? How can I connect to a replicaset? Read from slave and write to master?

**Comment by rochacbruno** [comment]
Quokka is built on top of MongoEngine and this supports ReplicaSets, But replica sets are not implemented directly on Quokka queries.

I was reading about about and found that you can pass a multiple connection string.

MONGODB_HOST = 'mongodb://localhost:27017,localhost:27018/'

But I have to figure out if works and do some tests, I guess the best way will be to implement a base queryset class or overwrite the managers to use Replicas as in http://docs.mongoengine.org/en/latest/guide/connecting.html#replicasets

**Comment by rochacbruno** [comment]
Fixed
