### ISSUE TITLE
Is it MIT License?

### ISSUE THREAD

**Issue by ghost** [quokkaproject/quokka#129]
The license in the license file seems to be MIT but not explicitly mentioning the license by its name makes the reader spend time on trying to figure out which license it is, if there are any changes to the standard license template or additional clauses to the license.

Mentioning the license name at the top of the license would help.

Also, mentioning the license name at end of readme and linking to, seems to be the norm. Example: https://github.com/saintedlama/passport-local-mongoose#license

If it is OK, I am updating both files, license and readme and sending a pull request.

**Comment by rochacbruno** [comment]
Thanks.
