### ISSUE TITLE
Changing password stores new password in plaintext.

### ISSUE THREAD

**Issue by WetDesertRock** [quokkaproject/quokka#132]
As seen here:
https://github.com/pythonhub/quokka/blob/master/quokka/modules/accounts/admin.py#L24

``` python
    def on_model_change(self, form, model, is_created):
        if model.newpassword:
            model.set_password(model.newpassword, save=True)
```

newpassword is stored in the model, and then saved into the database. I would suggest something like:

``` python
    def on_model_change(self, form, model, is_created):
        if model.newpassword:
            setpwd = model.newpassword
            del model.newpassword
            model.set_password(setpwd, save=True)
```

Also, using this type of scheme if you leave a field blank, it will blank out the field in the database.

**Comment by ellisonleao** [comment]
:+1:

**Comment by rochacbruno** [comment]
:+1:  got it, I will change it.
