### ISSUE TITLE
Unable to install - import errors from flask_misaka

### ISSUE THREAD

**Issue by GraphGrailAi** [quokkaproject/quokka#135]
I was unable to install Quokka:

First, i faced problems on Windows 7: bcrypt was not installed among other packages, (i solved this: i found 0.3.1 version compiled for windows.)

Second, when run 'python manage.py populate' i got an error cannot import HTML_ESCAPE. I solved this by commenting its import in file d:\WinPython-32bit-2.7.5.1\python-2.7.5\Lib\site-packages\flask-misaka.py  (i know that is bad way). Then i saw the same errors, so i commented imports 
# TABLE_ALIGNMASK,

```
#TABLE_ALIGN_C,
#TABLE_ALIGN_L,
#TABLE_ALIGN_R,
#TABLE_HEADER
```

and a little below in this file:

ALIAS_RENDER = {
    #'escape': HTML_ESCAPE,

And only after that i was able to install and runserver. 
All works, except http://127.0.0.1:5000/admin/mediagalleryview/ , http://127.0.0.1:5000/admin/postview/ ,  http://127.0.0.1:5000/admin/linkview/ ,  http://127.0.0.1:5000/admin/channelview/   - on these pages i got the same error:

jinja2.exceptions.UndefinedError

UndefinedError: 'quokka.modules.posts.admin.PostAdmin object' has no attribute '_get_filter_dict'

**Comment by rochacbruno** [comment]
I will replace misaka with another markdown parser.

**Comment by GraphGrailAi** [comment]
Ok, i will wait for this issue to be solved. 
I want to use Quokka for my project, because  i took several days going through multiple tutorials with Django i found in net - tried django-nonrel with mongodb-engine, and other options. I am really frustrated, because i cannot find full working tutorials and apps on github, some of them works, but with unexpected errors.
Soi think Flask will be an answer

**Comment by DiegoYungh** [comment]
1) Yes bcript should be used binaries instead.

2) As you are using windows like me, you need to compile misaka from source with 

```
pip install misaka --upgrade
```

Here it failed because I use VC9 to compile and it doesnt have **stdint.h**
You can find it on VC10 includes folder: _C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include_ and then paste on _C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include_

3) I have the same problem looking here...

**Comment by DiegoYungh** [comment]
Until now it's the following:

I commented on cosmo theme:

```
{# admin_view._get_filter_dict()|tojson|safe #},
{# filter_data|tojson|safe #},
{# filter_types|tojson|safe #}
```

They're on quokka/themes/cosmo/templates/admin/model/list.html L159
It's probably inheritance problem

**Comment by GraphGrailAi** [comment]
DiegoYungh - I commented all 3 strings and all admin views now works! As i understand this will not cause any errors, it simply removes some functionality: i see now that "Add filter" button doesn't work.

The next question is where i can find tutorial on how to extend Quokka with my apps? For example I have an example app from http://docs.mongodb.org/ecosystem/tutorial/write-a-tumblelog-application-with-flask-mongoengine/ - what is the workflow?

**Comment by DiegoYungh** [comment]
There's one here: https://github.com/pythonhub/quokka/wiki/plugins
Please fell free to create new modules to the community

**Comment by GraphGrailAi** [comment]
DiegoYungh -  i saw that, but where is the docs? By the way in quokka\quokka\modules\posts\ there is no templates folder

**Comment by DiegoYungh** [comment]
This is all the docs for now :)

The template is inherited in this case.
As Post comes from _Content_

We may found something on: quokka/templates/content/

You can check rendering defaults on Quokka/core/views[ContentList, ContentDetail]
The rendering logic is based on what you see here.

**Comment by DiegoYungh** [comment]
I think the Issue itself has been bypassed ^^
