### ISSUE TITLE
ImportError: PIL library was not found when create Post

### ISSUE THREAD

**Issue by GraphGrailAi** [quokkaproject/quokka#136]
I am trying to create new post from admin, got an error: ImportError: PIL library was not found

File "D:\WinPython-32bit-2.7.5.1\python-2.7.5\lib\site-packages\flask_admin\form\upload.py", line 335, in **init**

raise ImportError('PIL library was not found')

I dive into this file and this is very strange: I have PIL library installed (from here http://www.pythonware.com/products/pil/) and when i import it like there on line 23

from PIL import Image, ImageOps

there is no errors in Pycharm. So why PIL is not found?

**Comment by DiegoYungh** [comment]
I guess it's being supressed...

Look closer on the import:

```
try:
    from PIL import Image, ImageOps
except ImportError:
    Image = None
    ImageOps = None
```

Are you using a virtualenv, if then check if PIL is intalled there

**Comment by DiegoYungh** [comment]
My Image class is in PIllow

```
<module 'PIL.Image' from 'C:\bin\Python27\lib\site-packages\pillow-2.0.0-py2.7-win32.egg\PIL\Image.py'>
```

**Comment by DiegoYungh** [comment]
And keep this in your favorites, windows users must have binaries on hand
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by GraphGrailAi** [comment]
I use this binaries too. No, i don't use virtualenv. Now installed Pillow - no any changes

**Comment by DiegoYungh** [comment]
In this case, you can try the following:
- Check if PIL and Pillow are installed on the right python version
- Put a Print on _flask_admin\form\upload.pyL334~_ to check sys.path on that moment
