### ISSUE TITLE
Error on travis build

### ISSUE THREAD

**Issue by ellisonleao** [quokkaproject/quokka#138]
There is an error on dowloading the twill repo, which is causing an error on building the tests. This doens't occurs locally, i guess it's a problem with the Travis servers 

```
Downloading/unpacking twill (from -r requirements_test.txt (line 29))
  Could not find any downloads that satisfy the requirement twill (from -r requirements_test.txt (line 29))
  Some externally hosted files were ignored (use --allow-external twill to allow).
Cleaning up...
No distributions at all found for twill (from -r requirements_test.txt (line 29))
Storing debug log for failure in /home/travis/.pip/pip.log
```

**Comment by cassiobotaro** [comment]
This error occurs here too at my machine. I use `pip install twill --allow-external twill --allow-unverified twill` and then `pip install -r requirements` again.

**Comment by ellisonleao** [comment]
Thanks @cassiobotaro , you and travis gave the hint about the --allow-external variables and that fixed it.

**Comment by rochacbruno** [comment]
:+1:
