### ISSUE TITLE
Problem with postview

### ISSUE THREAD

**Issue by cassiobotaro** [quokkaproject/quokka#139]
When i run http://127.0.0.1:5000/admin/postview/ i gave this error: UndefinedError: 'quokka.modules.posts.admin.PostAdmin object' has no attribute '_get_filter_dict'
It's a clean installation step by step following the README.md file.

**Comment by cassiobotaro** [comment]
This error repeat at http://127.0.0.1:5000/admin/configview/.

**Comment by rochacbruno** [comment]
Maybe it is a change in Flask-Admin, I am testing it..

**Comment by rochacbruno** [comment]
It was a change in Flask-Admin macros, I changed all the admin templates in cosmo theme.
