### ISSUE TITLE
Fix admin top menu align

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#140]
with the #139 fix I introduced a css problem in the admin menu css.

The dropdown button in access_control block is not aligned.

Need a CSS expert to fix this.

All files under /cosmo/ theme

**Comment by DiegoYungh** [comment]
@ellisonleao  already merged :+1: 
Looks right here: http://grab.by/vJ9K

**Comment by rochacbruno** [comment]
:+1:
