### ISSUE TITLE
question: size of thumbnail images

### ISSUE THREAD

**Issue by ottk3** [quokkaproject/quokka#143]
I haven't found anything in the code. How are the image thumbnails created? Can i modify the size (atm 100x100) or create medium images?

**Comment by rochacbruno** [comment]
Thats defined here: https://github.com/pythonhub/quokka/blob/master/quokka/modules/media/admin.py#L117

You can set in your settings.py or in your local_settings.py or throught the admin interface under config menu.

```
MEDIA_IMAGE_THUMB_SIZE = (100, 100, True)
```

The last "True" stands for "keep aspect ratio" to not shrink the image

**Comment by ottk3** [comment]
great! thx! :)
