### ISSUE TITLE
How can I use flask-cache in quokka?

### ISSUE THREAD

**Issue by lazygunner** [quokkaproject/quokka#144]
I found 

```
def configure_extensions(app, admin):
    babel.configure(app)
    generic.configure(app)
    Cache(app)
    Mail(app)
```

in quokka/ext/init.py. How can I use cache in my module?

**Comment by rochacbruno** [comment]
In Quokka the Flask-Cache is initialized and you can use it normally in your views and templates for your modules. refer to flask-cache docs -> http://pythonhosted.org/Flask-Cache/

unfortunatelly it is not yet implemented in Quokka core, but it is planned to have optional cache for all core views and templates.

**Comment by DiegoYungh** [comment]
Would be cool to have a @Cache decorator like this :+1: 
http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/cache.html

**Comment by rochacbruno** [comment]
@DiegoYungh there is! take a look in flask-cache docs

**Comment by DiegoYungh** [comment]
Cool!
And there's even a template tag to cache.

Decorator

```
@cache.cached(timeout=50)
```

Templatetag

```
{% cache 60*5 %}
... content
{% endcache %}
```

I will test it later I can see how can I pass
- maxage
- smaxage
- expires

I am sure they provided it somehow in advanced mode, I see I can pass a list of extra arguments and stuff, there is only one way... testing!

I loved it :+1:

**Comment by lazygunner** [comment]
@rochacbruno Thanks for the help! Hope the cache will be added to Quokka core sooner!
