### ISSUE TITLE
WTForms 2.0 TypeError

### ISSUE THREAD

**Issue by jhuss** [quokkaproject/quokka#150]
in a fresh installation pip install WTForms 2.0 from requirements.txt
but WTForms 2.0 fall into TypeError when try to load any form, the issue is reported in flask-admin: https://github.com/mrjoes/flask-admin/issues/541

the solution is downgrade WTForms to 1.0.5 and add version limit on requirements.txt

**Comment by rochacbruno** [comment]
@jhuss done! Thank you.

**Comment by abnerpc** [comment]
requirements_test.txt also needs this one...
