### ISSUE TITLE
question: How to serve from localhost/blog instead of just localhost?

### ISSUE THREAD

**Issue by repole** [quokkaproject/quokka#154]
Apologies if this is obvious, but I'm trying to run quokka with /blog as its root and am unable to find a setting I can change to accomplish that.

**Comment by rochacbruno** [comment]
Are you trying to serve 2 Python/wsgi applications at the same server:port?

look at this http://flask.pocoo.org/docs/patterns/appdispatch/#combining-applications

I never thought about that in quokka, but there is a way you can place a file at the root directory and serve from there.

There is already a wsgi.py https://github.com/pythonhub/quokka/blob/master/wsgi.py

you can create another file changing to

# wsgi_changed.py

``` python
from werkzeug.serving import run_simple
from werkzeug.wsgi import DispatcherMiddleware

from quokka import create_app

application = DispatcherMiddleware("YOUR ROOT WSGI APP GOES HERE" , {
    '/blog': create_app()
})

if __name__ == "__main__":
    run_simple(
        '0.0.0.0',
        5000,
        application,
        use_reloader=True,
        use_debugger=True
    )

```

**Comment by rochacbruno** [comment]
and if you dont have a root app yet, you can just put a dummy app there

``` python

from flask import Flask
...
...
application = DispatcherMiddleware(Flask(__name__) , {
    '/blog': create_app()
})

...
```

**Comment by repole** [comment]
Apologies for the late response, really appreciate the help.

This gets the job done for the most part, there are a few work arounds needed for anything served via absolute paths (static files for example), but it isn't too much effort. A setting that's configurable in settings.py would be really convenient, though I'm not sure if the effort to implement that is worth the payoff.
