### ISSUE TITLE
Quokka not installed in virtualenv via install script on ubuntu12.04

### ISSUE THREAD

**Issue by mukul-kumar** [quokkaproject/quokka#157]
The install script for ubuntu 12.04 installed the quokka globally and not in the virtualenv.

**Comment by ghost** [comment]
Activate the `virtualenv` and run `pip install quokka`

**Comment by rochacbruno** [comment]
@mukul-kumar I will take a closer look in the scripts next week. @itsnauman unfortunatelly the PyPI version is outdated (and also useless, maybe it will become a meta-package)

Is it a good idea to have a vagrant box? a Puppet/chef recipe?

**Comment by rochacbruno** [comment]
fixed in script
