### ISSUE TITLE
WSGI with apache : Module cannot be found

### ISSUE THREAD

**Issue by rico-bee** [quokkaproject/quokka#158]
I am trying to configure QUOKKA from apache via wsgi.

However I got some error:

[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx] mod_wsgi (pid=16559): Target WSGI script '/data/rzh/quokka/wsgi.py' cannot be loaded as Python module.
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx] mod_wsgi (pid=16559): Exception occurred processing WSGI script '/data/rzh/quokka/wsgi.py'.
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx] Traceback (most recent call last):
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx]   File "/data/rzh/quokka/wsgi.py", line 19, in <module>
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx]     application = DispatcherMiddleware(create_app(), {
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx]   File "/data/rzh/quokka/quokka/**init**.py", line 28, in create_app
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx]     app = QuokkaApp('quokka')
[Wed Jul 02 14:24:48 2014] [error] [client xxxxxxxxxxxxxxxxx] NameError: global name 'QuokkaApp' is not defined

my wsgi entry file looks like this:

```
# -*- coding: utf-8 -*-
import os,sys
virtenv = '/data/rzh/py2.7/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
        execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
        pass

sys.path.insert(0, '/data/rzh/quokka')
sys.path.insert(1, '/data/rzh/quokka/quokka')


from werkzeug.serving import run_simple
from werkzeug.wsgi import DispatcherMiddleware

from quokka import create_app, create_api

application = DispatcherMiddleware(create_app(), {
    '/api': create_api()
})

if __name__ == "__main__":
    run_simple(
        '0.0.0.0',
        5000,
        application,
        use_reloader=True,
        use_debugger=True
    )
```

Please help me with this,, many thanks

**Comment by rochacbruno** [comment]
There is a problem here https://github.com/pythonhub/quokka/blob/master/quokka/__init__.py#L21 maybe you do not need this line `sys.path.insert(0, '/data/rzh/quokka')` somthing related to the path

**Comment by rico-bee** [comment]
If I remove `sys.path.insert(0, '/data/rzh/quokka')`, it doesn't find the quokka module even.

strangely if I do `python wsgi.py`, it runs locally pretty well.

The problem is only when I run via apache.

**Comment by rico-bee** [comment]
I figured it out. The reason is that my mod_wsgi is still linked to python 2.6 so even I activate the virtualenv in the app, it still runs from python 2.6.

**Comment by yasoob** [comment]
@rochacbruno this issue is good to close.
