### ISSUE TITLE
quokka/themes/cosmo/static/admin/js/forms.js

### ISSUE THREAD

**Issue by postcapital** [quokkaproject/quokka#159]
Is this broken? none of the dynamic admin forms eg. "Add Content" work in the current master after May commit to other files changing names.

**Comment by rochacbruno** [comment]
Hi, I will check, it seems that there is a new version of Flask-Admin and it broke the theme.

**Comment by postcapital** [comment]
I see now how it works and I got this form working again copying the new Flask-Admin forms.js file into quokka/themes/cosmo/static/admin/js which is a relief.  I also updated jquery but 
I am basicallly unable to change the admin theme in settings.py, is 'cosmo' the only theme allowed for admin?

**Comment by rochacbruno** [comment]
Try going to admin, config and changing that value there instead of settings. Just to see if it works. maybe there is a bug in the order that configs are loaded.

**Comment by postcapital** [comment]
okay using this setting it is possible to change the theme however it breaks, the theme needs Flask-Admin templates  TemplateNotFound: admin/custom/prepopulated.html
It would obviously be great to remove the modified Flask-Admin code from quokka and I will look into this.

**Comment by rochacbruno** [comment]
This template is needed to generate the slug in Post admin, but we need to find a way to host it in a separate place, or load it dinamicaly via template tag.

**Comment by rochacbruno** [comment]
related to #201
