### ISSUE TITLE
'path': form.FileUploadField (quokka/quokka/core/models.py)

### ISSUE THREAD

**Issue by javalurker** [quokkaproject/quokka#16]
at 367 line: 'path': form.FileUploadField 
error information:
AttributeError: 'module' object has no attribute 'FileUploadField'

flask-admin 1.0.6(installed)

**Comment by rochacbruno** [comment]
Can you please try installing form git

pip install https://github.com/mrjoes/flask-admin/tarball/master

or 

pip install -e git+https://github.com/mrjoes/flask-admin#egg=flask-admin

FileUpload was introduced by @mrjoes in early versions of development branch.

So in Quokka requirements it is specified to install from github https://github.com/pythonhub/quokka/blob/master/requirements.txt#L19

Please try and let me know if it works.

**Comment by javalurker** [comment]
i installed it from git
pip install https://github.com/mrjoes/flask-admin/tarball/master

now,it works very well.

**Comment by rochacbruno** [comment]
I will add a note on readme. Thanks
