### ISSUE TITLE
Blueprint name collision on module install

### ISSUE THREAD

**Issue by pixiemars** [quokkaproject/quokka#160]
I have started a new module using cookie cutter, everything goes well until I restart the server. At this point I get:

AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0x7f37e6ca8610> and <quokka.core.app.QuokkaModule object at 0x7f37eb1b8e10>.  Both share the same name "quokka_events".  Blueprints that are created on the fly need unique names.

The same thing happens when I try install the shopping cart module.

Any help will be appreciated.

**Comment by pixiemars** [comment]
Any help here?

**Comment by ellisonleao** [comment]
i will take a look ASAP @pixiemars .

**Comment by rochacbruno** [comment]
I just installed the cart module in a clean installation and nothing happens, whats your config? Python version and O.S?

**Comment by pixiemars** [comment]
Hiya

Sorry for the delay. Too many projects on the go! Its Ubuntu 14.04 and Python 2.7.x

I will try with a fresh install on Monday.

**Comment by yasoob** [comment]
@pixiemars how did the fresh install go?

**Comment by rochacbruno** [comment]
Verified installed all modules, no error found.
