### ISSUE TITLE
Add Push To PaaS (Heroku, OpenShift, PythonAnywhere?) Button?

### ISSUE THREAD

**Issue by ghost** [quokkaproject/quokka#163]
How about we add a button to the `README` so that people can deploy to GitHub with one click :smiley:

**Comment by yasoob** [comment]
I guess it's better to submit a pull request and then ask.

**Comment by ellisonleao** [comment]
i am working on this feature for the past week, should be done soon.

**Comment by rochacbruno** [comment]
@ellisonleao OpenShift has a free cartridge for Mongo, we can try to add an OpenShift cartridge for Quokka

**Comment by rochacbruno** [comment]
Did not found a service providing free mongoDB hosting + Flask/Python hosting

**Comment by rochacbruno** [comment]
Running on OPenShift http://wercker-rochacbruno.rhcloud.com/

Deployment configured using wercker

needs documentation

**Comment by rochacbruno** [comment]
found this https://github.com/openshift-quickstart/flask-base there is a lauch on OpenShift button

**Comment by rochacbruno** [comment]
trying this https://hub.openshift.com/quickstarts/175-quokkacms

**Comment by rochacbruno** [comment]
Done!

https://hub.openshift.com/quickstarts/175-quokkacms

There is a button on README "launch on OpenShift" one click and done!

[![Launch on OpenShift](http://launch-shifter.rhcloud.com/button.svg)](https://openshift.redhat.com/app/console/application_type/custom?cartridges%5B%5D=python-2.7&cartridges%5B%5D=mongodb-2.4&initial_git_url=https://github.com/quokkaproject/quokka.git&name=quokka&initial_git_branch=development)
