### ISSUE TITLE
Content not showing in related_channels

### ISSUE THREAD

**Issue by postcapital** [quokkaproject/quokka#166]
Content is not showing in related channels for me, is there something you have to do?

**Comment by rochacbruno** [comment]
I will take a look.

**Comment by postcapital** [comment]
Did this ever work at all?  I've had a good look at the code but can't quite work it out if this has ever been implemented, unfortunately it's essential for a site i'm trying to make.

**Comment by hypknowsys** [comment]
Hi there, 
actually I have the same question. When I check related channels the content will not be shown in the channel. @rochacbruno Can you give us a "hot file" where to look?

Thanks

**Comment by rochacbruno** [comment]
This should be implemented in core/views I am looking on this

**Comment by rochacbruno** [comment]
This is a very hot issue, here is the place where the Mongo query should include content from every content with relation

https://github.com/quokkaproject/quokka/blob/master/quokka/core/views.py#L99

**Comment by rochacbruno** [comment]
Done! @hypknowsys
