### ISSUE TITLE
Error on instalation in OSX 10.8

### ISSUE THREAD

**Issue by londerson** [quokkaproject/quokka#167]
Well, i try installing and got these erros after run the command $ pip install -r requirements.txt

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/_imaging.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/decode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/encode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/map.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/display.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/outline.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/path.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Access.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/AlphaComposite.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Antialias.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Bands.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/BitDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Blend.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Chops.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Convert.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/ConvertYCbCr.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Copy.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Crc32.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Crop.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Dib.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Draw.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Effects.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/EpsEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/File.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Fill.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Filter.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/FliDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Geometry.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/GetBBox.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/GifDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/GifEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/HexDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Histo.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/JpegDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/JpegEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/LzwDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Matrix.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/ModeFilter.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/MspDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Negative.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Offset.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Pack.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/PackDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Palette.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Paste.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Quant.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/QuantOctree.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/QuantHash.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/QuantHeap.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/PcdDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/PcxDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/PcxEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Point.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/RankFilter.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/RawDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/RawEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Storage.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/SunRleDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/TgaRleDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Unpack.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/UnpackYCC.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/UnsharpMask.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/XbmDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/XbmEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/ZipDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/ZipEncode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/TiffDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Incremental.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Jpeg2KDecode.o'

clang: error: no such file or directory: 'build/temp.macosx-10.8-intel-2.7/libImaging/Jpeg2KEncode.o'

error: command 'clang' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/private/var/folders/m5/t7lxkrz95d34s1qkqljd_4n80000gn/T/pip_build_londerson/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/m5/t7lxkrz95d34s1qkqljd_4n80000gn/T/pip-COqmtB-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/m5/t7lxkrz95d34s1qkqljd_4n80000gn/T/pip_build_londerson/Pillow
Storing debug log for failure in /Users/londerson/Library/Logs/pip.log

**Comment by rochacbruno** [comment]
There is a Pillow issue https://github.com/python-pillow/Pillow/issues/27

**Comment by ellisonleao** [comment]
Do you have XCode with the dev tools installed @Londerson  ? This error sounds like it's a problem with it.

**Comment by londerson** [comment]
I will follow the advice of yours, and will report the results before closing the issue. Thanks for the support staff!

**Comment by ellisonleao** [comment]
any updates on this @Londerson  ?

**Comment by rochacbruno** [comment]
Closing because now we have docker image and it can run on OS X
