### ISSUE TITLE
Channels and SubChannels - other solutions

### ISSUE THREAD

**Issue by hypknowsys** [quokkaproject/quokka#168]
Hi there, 
I am not sure whether this is the best solution, so I will give it a try:

For ordering my content I create different channels,  let's say
Channel 1: project
Channel 2: project/projectA/documentation
Channel 3: project/projectA/code/python
Channel 4: project/projectA/code/java

When I place now some stuff in Channel 3 and I call Channel 1 all the stuff form Channel 2, 3, 4 will be displayed. 
What I did: checking for the slug, compare the path, if the current channel path is equal to the channel path of the entry it will be displayed. 

 {% set current_content = content.long_slug  |replace(content.slug , "")  %}
 {% set current_channel = channel.long_slug + '/'    %}

 {% if current_content  ==   current_channel %}
            <p>The content will be displayed </p>
 {% endif %}

Question: is there a better solution? 

Thanks in advance

**Comment by rochacbruno** [comment]
In your case, the "project" channel is the root channel, why you don't need the stuff under it to be showed?

You can have a new template type for this channel and use your solution, but if this is a common need we can ass some flag like "display_child_content" to be configured by channel.

**Comment by hypknowsys** [comment]
Hi Rocha,

thanks for reply. 

I am using your CMS (btw: great stuff) as Service Catalog (have a look for example at http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/): first Page: only Buttons linking to the sub content (like "User Modeling" in the page) 
Under 'User Modeling' I have a short description, longer description, Code, Live Demo. This means I have actual 4 pages. 
That's why I need the filter.
I will continue working on this today. At the moment the workaround is fine for me. I will give you an update. 

Thanks for you help.

**Comment by rochacbruno** [comment]
WOW! Nice to know that you are using it in IBM!

I will put some effort to have the filter!

**Comment by rochacbruno** [comment]
@hypknowsys is it allowed to announce your project as Quokka use case?

I am preparing a page "who is using Quokka"

**Comment by rochacbruno** [comment]
ok! @hypknowsys

**Comment by jniltinho** [comment]
Bacana heim Bruno
Em 11/11/2014 11:38, "Bruno Rocha" notifications@github.com escreveu:
