### ISSUE TITLE
Redirects for changed urls

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#17]
Implemented history of changed urls for redirects

**Comment by jonasteuwen** [comment]
I would be interested in implementing this. What would be the 'Quokka' way of doing this? Nginx redirect with say lua_nginx is not good?

**Comment by rochacbruno** [comment]
This is meant to work just like the Django reqdirect framework, I don't know how to do it in werkzeug yet.

The idea is to create the redicrect entry in the core.models.Slugged class, we need to detect a change in slug and record the redirect rule on to Redirect model.

Redirect models should be: `Redirect.old_path, Redirect.new_path, Redirect.created_at`

So

Content have a channel/slug i.e:  `/channelname/content-slug.html`

If the editor by some reason needs to change the content to another channel `/anotherchannel/content-slug.html` in this case we need to create a redirect entry
- Redirect.old_path: `/channelname/content-slug.html`
- Redirect.new_path: `/anotherchannel/content-slug.html`

**consider subchannels** `/anotherchannel/subchannel/subsubchannel/.../content-slug.html`

The same if editor needs to change the content slug:
- REdirect.old_path: `/channelname/content-slug.html`
- Redirect.new_path: `/channelname/another-content-slug.html`

Thats the easiest part!

Now the problem is to deal with this in the werkzeug dispatcher, the workflow should be:

a client requests `/channelname/content-slug.html` that content is not found, before we raise a 404 we go to the **Redirect** and we try to find objects for that path `Redirect.objects.get(old_path='/channelname/content-slug.html')`  if found we redirect the user to the `new_path` 

> IMPORTANT: take a look on how Django resolve the problem of infinite redirect loop if it happens.

Thats the idea, do you know how to deal with it in werkzeug dispatcher? maybe overriding the part which deals with 404.

Thank you.

**Comment by jonasteuwen** [comment]
Hi,

Thanks for your extensive reply. I do not know how to deal with it in the werkzeug dispatcher, but I'll study its code a bit better for this purpose.

Ideally I would also like to have 'manual' redirects, say go.<domain.tld>/bbq -> <domain.tld>/events/2013/barbecue or so. Will look into it.

**Comment by rochacbruno** [comment]
> Ideally I would also like to have 'manual' redirects, say go./bbq -> /events/2013/barbecue or so. Will look into it.\

It can be done in admin, registering **Redirect** model in admin and users can insert redirect rules in the form.

**Comment by rochacbruno** [comment]
some links to help:

http://stackoverflow.com/questions/8069846/dynamically-add-url-rules-to-flask-app

http://flask.pocoo.org/docs/api/#url-route-registrations

http://flask.pocoo.org/docs/patterns/appdispatch/

**Comment by jonasteuwen** [comment]
Thanks!

That is something I am aware of. My idea was yours from above and quite pythonic: attempt to fetch and catch the error. Need some experimenting for that.

**Comment by mauricioabreu** [comment]
Hello,

What do you think about this approach?

``` python
try:
            redirect_path = Redirect.objects.get(old_path=long_slug)
            return redirect(url_for('detail', long_slug=redirect_path.new_path))
        except DoesNotExist:
            try:
                content = Content.objects.get(
                    long_slug=long_slug,
                    published=True,
                    available_at__lte=now
                )
            except Content.DoesNotExist:
                content = Content.objects.get_or_404(
                    channel=homepage,
                    slug=long_slug,
                    available_at__lte=now,
                    published=True
                )
```

**Comment by jonasteuwen** [comment]
I prefer to separate it a bit, we could make a custom exception for this, for normal documents **get_or_404** is used, so then:

```
@app.errorhandler(404)
def page_not_found(e):
     # some custom stuff to check redirects documents
    return redirect(link_target, code=303)
```

Nothing to change then (=good), but just let the dispatcher raise a 404, and the errorhandler catch it and do its thing. While we are at it, we can dispatch some signals which can be used to compile some statistics to inform the administrators why the heck many people need the redirect.

An idea of Flask is a bit that it is lightweight and better to hook many small applications together than building a large one. 

Would this be implemented as a module? Perhaps we can just extend **Post** and put the stuff in a module. I'll give it a shot, was quite busy lately.

**Comment by rochacbruno** [comment]
There is already error handlers here: https://github.com/pythonhub/quokka/blob/master/quokka/ext/error_handlers.py#L20

**Comment by jonasteuwen** [comment]
Yes, I know, but do you want it to be possible to modify the error handlers in a module?

Also, the **ObjectId** has the property **generation_time** which -I think- removes the need for created_at.

**Comment by rochacbruno** [comment]
I don't think it is necessary, the module should be limited because it needs to follow some url rules, I mean, every module should extend "Content" class in order to get content urls exposed.

So if one creates a **Poll** module, will need to do `class Poll(Content)` and the Poll content will be acessible by the same url pattern as a **Post**, `/channel/subchannel/this-is-the-poll-slug`, maybe we can force each module to register a channel for itself `/poll/subchannel/this-is-the-poll-slug` where **/poll/** is the default channel for polls.

In this way modules will not need to register **views** and **urls** for content, maybe the module will register views and urls for actions like **vote** and other APIs.

Do you imagine a case where it will be needed to define error_handler inside a module?

**Comment by jonasteuwen** [comment]
Yes, but maybe it does not fit the above scheme. I imagined a module to be a small extension, not just in a way of presenting content, but also functionality. Say we would have a JSON API, you would want the error-handlers to return JSON and a JSON endpoint too, and we could put that in a module. Will think a bit about the rest.

**Comment by mauricioabreu** [comment]
I agree, that code in the view is not good, I know. I was just giving you a start.
A redirect handler approach is good because every model which has a long_slug could be used to perform a redirect.
Imagine if you have a new extension of Post. Probably the code I gave would be replicated which is a very bad idea, so a handler to it will be clear enough like Bruno said.

**Comment by jonasteuwen** [comment]
Alright,

How about this: https://gist.github.com/jonasteuwen/6649639?

It is taken form Flask-Exception, but it catches the http_error_handler and looks through the Redirect model for a redirect else continue with Flask exception handling else redirect. This avoids having to add the code to the eror handler itself. The lookup is a bit hacked together, but I wanted a quick test.

Also, https://github.com/SimonSapin/Flask-WeasyPrint/blob/master/flask_weasyprint/__init__.py Flask-Wheezyprint has a nice solution for redirect loops:

```
    def flask_url_fetcher(url):
        redirect_chain = set()
        while 1:
            result = dispatcher(url)
            if result is None:
                return next_fetcher(url)
            app, base_url, path = result
            client = Client(app, response_wrapper=Response)
            if isinstance(path, unicode):
                # TODO: double-check this. Apparently Werzeug %-unquotes bytes
                # but not Unicode URLs. (IRI vs. URI or something.)
                path = path.encode('utf8')
            response = client.get(path, base_url=base_url)
            if response.status_code == 200:
                return dict(
                    string=response.data,
                    mime_type=response.mimetype,
                    encoding=response.charset,
                    redirected_url=url)
            # The test client can follow redirects, but do it ourselves
            # to get access to the redirected URL.
            elif response.status_code in (301, 302, 303, 305, 307):
                redirect_chain.add(url)
                url = response.location
                if url in redirect_chain:
                    raise ClientRedirectError('loop detected')
            else:
                raise ValueError('Flask-WeasyPrint got HTTP status %s for %s%s'
                                 % (response.status, base_url, path))
    return flask_url_fetcher
```

**Comment by mauricioabreu** [comment]
actually a forced redirect is not a http error. But your hack looks good.
Em 21/09/2013 11:24, "Jonas Teuwen" notifications@github.com escreveu:

**Comment by jonasteuwen** [comment]
Well, it is a 404, the content does not exist anymore. For the convenience of the user we redirect him to where he should have been in the first place :-).

**Comment by rochacbruno** [comment]
What if you create a reusable app called `Flask-Redirect` which expects a Model having new_path, old_path or something like this?

Then `init_app` can be rewriten to receive this model as parameter.

```
from flask import Flask
from flask.ext.redirect import Redirector
from someplace import RedirectModel

app = Flask()

redirector = Redirector(model=RedirectModel, new_field="new_path", old_field="old_path")
redirector.init_app(app)
```

Then we have a generic **Redirect** app for Flask and can use this for Quokka.

**Comment by jonasteuwen** [comment]
That's a good idea. Will do!

**Comment by rochacbruno** [comment]
Link is already implemented with this redirect feature, now just need to detect a name/slug changing to create a link
