### ISSUE TITLE
channel list on template

### ISSUE THREAD

**Issue by mvmthecreator** [quokkaproject/quokka#170]
how to display list of all channels and subchannels in theme template ?

**Comment by rochacbruno** [comment]
"channels" is exposed for templates so you can use 

https://github.com/quokkaproject/quokka/blob/master/quokka/themes/default/templates/base.html#L174

and

https://github.com/quokkaproject/quokka/blob/master/quokka/themes/default/templates/_menu.html#L10

Like it is used in right sidebar
