### ISSUE TITLE
Javascript on admin page broken - FIX

### ISSUE THREAD

**Issue by hypknowsys** [quokkaproject/quokka#172]
Hi there,

the buttons for "Add values", "Add contents" and "Add tags" are broken. Reason is method onclick="faForm.addInlineField ..." 

As I found out you are using flask-admin. Flask admin changed the corresponding "form.js". Method addInlineField changed from 

this.addInlineField = function(el, elID, template)
to
this.addInlineField = function(el, elID) 

You already changed the <a> tag in the  template, but you still have the old form.js in your github repository.   That's why it is not working. Can somebody check in the new version. Or should I do it?

Thanks 

H

**Comment by ellisonleao** [comment]
Hey @hypknowsys you can create a PR if you fix the problem. That is much appreciated :smile:

**Comment by hypknowsys** [comment]
OK, will be the first task tomorrow. 

H
