### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#179]
I am new to this but I love what you guys are doing. I found one of you on reddit mentioning you were developing this while I was searching for a python blog engine. I would love to follow you and run this software on my personal site. I have set it up and have come across my first bug so I would like to help you by showing you it. I don't think it's anything I am doing wrong and the install went fine. The problem is when I try to delete content. I have attached a screenshot. It does this whether I delete existing content, or create content and then try to delete it. I would like very much to be a tester for you. If you are interested please let me know where I can look to fix this problem as I am also looking to learn how to code! Keep up the good work!

**Comment by eurabilis** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/11414554/6585835/3abff472-c74b-11e4-9144-32bc563b2194.png)

**Comment by rochacbruno** [comment]
Fixed in #201
