### ISSUE TITLE
werkzeug "GET /admin/static/admin/js/actions.js HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#180]
Is anyone still alive around here is this project being worked on? :) Another problem I have is it never seems to find this file so I cant tick and delete in the admin interface. The only trace of that file I see is in the below directory. I tried moving it around but it didnt work. Where is it supposed to be and why is it missing or looking in the wrong spot? Thanks.
/home/quokkaenv/quokka/quokka/themes/cosmo/static/admin/js/actions.js

**Comment by Shaunakde** [comment]
Hey,

I am new to the project, but I would like to try and address this. I dont
think I fully understand your problem but let me see if I can figure it out
in a couple of hours post work

SD

On Mon, Mar 23, 2015 at 7:24 AM, eurabilis notifications@github.com wrote:

> Is anyone still alive around here is this project being worked on? :)
> Another problem I have is it never seems to find this file so I cant tick
> and delete in the admin interface. The only trace of that file I see is in
> the below directory. I tried moving it around but it didnt work. Where is
> it supposed to be and why is it missing or looking in the wrong spot?
> Thanks.
> /home/quokkaenv/quokka/quokka/themes/cosmo/static/admin/js/actions.js
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quokkaproject/quokka/issues/180.

## 

Shaunak De
http://shaunak.ws/

**Comment by eurabilis** [comment]
Thanks if I could just figure out these two bugs I posted I'd be very happy. I can't even seem to delete content that's there or after I create it. Does it matter that I have quokka in a virtualenv

**Comment by rochacbruno** [comment]
I think it is an issue with the Flask admin version, I will take a look

**Comment by eurabilis** [comment]
great bruno thanks its nice to finally meet you. You are doing good work this is the best blog sofware out there in python! I hope I was not being a pest I just want to help and learn to code. I gave my first bug two weeks of no one answering before I posted another one.

**Comment by abdounasser202** [comment]
Hello

I'm using ubuntu 13.04 LTS. I've tried to install quokka but when

creating /usr/local/lib/python2.7/dist-packages/flask

error: could not create '/usr/local/lib/python2.7/dist-packages/flask': Permission denied

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_bapetel/flask/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-xibGI5-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_bapetel/flask
Storing debug log for failure in /home/bapetel/.pip/pip.log

Help me please!

**Comment by ellisonleao** [comment]
Looks like this is a folder permission issue. Are you using a `virtualenv` ?

**Comment by abdounasser202** [comment]
no i don't

2015-03-27 19:11 UTC+01:00, Ellison Le�o notifications@github.com:

> Looks like this is a folder permission issue. Are you using a `virtualenv`
> ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quokkaproject/quokka/issues/180#issuecomment-87037337

## 

Abdou Nasser
�tudiant de bioinformatique
http://nasserzone.blogspot.com

**Comment by ellisonleao** [comment]
Can you try again, creating a virtual environment? You can follow the wiki

https://github.com/quokkaproject/quokka/wiki/installation

**Comment by abdounasser202** [comment]
i'll try

**Comment by abdounasser202** [comment]
I'm Abdou Nasser, a cameroonian who likes web programmaing in python and you?

**Comment by abdounasser202** [comment]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /home/bapetel/quokka-env/bin/python -c "import setuptools,
tokenize;**file**='/home/bapetel/quokka-env/build/Pillow/setup.py';exec(compile(getattr(tokenize,
'open', open)(**file**).read().replace('\r\n', '\n'), **file**,
'exec'))" install --record /tmp/pip-3MWbKy-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/bapetel/quokka-env/include/site/python2.7 failed with error code
1 in /home/bapetel/quokka-env/build/Pillow
Storing debug log for failure in /home/bapetel/.pip/pip.log

2015-03-27 19:14 UTC+01:00, Ellison Le�o notifications@github.com:

> Can you try again, creating a virtual environment? You can follow the wiki
> 
> https://github.com/quokkaproject/quokka/wiki/installation
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quokkaproject/quokka/issues/180#issuecomment-87038043

## 

Abdou Nasser
�tudiant de bioinformatique
http://nasserzone.blogspot.com

**Comment by eurabilis** [comment]
Hi abdou we also like web programming and python it's nice to meet you. I am just guessing but do you have build-essential installed? Try: sudo apt-get install build-essential

**Comment by rochacbruno** [comment]
fixed
