### ISSUE TITLE
I setup a support channel for quokka.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#183]
I set us up a channel for us to discuss bugs and sit there helping each other out. Just fire up your favorite irc client and go to irc.dontexist.dynu.com #quokka ill be there to help with whatever I can. Lets keep this repo clean of support questions so bruno and the others can work  on actually closing tickets. If you are good with python and quokka in general you should idle there if you have the time to answer questions. I hope to see you all there.

**Comment by rochacbruno** [comment]
There is also the Gitter Channel https://gitter.im/quokkaproject/quokka
