### ISSUE TITLE
Why not compatible python3?

### ISSUE THREAD

**Issue by 030io** [quokkaproject/quokka#188]
We should support the decision of the python community.
Although it is difficult, but we should try.

**Comment by rochacbruno** [comment]
:+1:

**Comment by ellisonleao** [comment]
easier said than done hehe. But let's do this! :+1:

**Comment by 030io** [comment]
I think we should start from the requirements of quokka.

**Comment by alexandre** [comment]
@030io ,

I'm working on this feature, please, check my pull request  #190 while @rochacbruno validates it. =]

P.S Quokka is the happiest project, so, the community will support the community. =]

**Comment by rochacbruno** [comment]
in progess #222
