### ISSUE TITLE
Cannot delete post, MongoDB error `Id: This field is required`

### ISSUE THREAD

**Issue by blakev** [quokkaproject/quokka#189]
I cannot delete posts...I get the above error. The best I can do is "not publish" and hide from the channels. Any idea how to fix easily? It's kind of annoying...

![image](https://cloud.githubusercontent.com/assets/4885156/7421140/5ba0e572-ef3f-11e4-8d84-b990ff0be648.png)

**Comment by rochacbruno** [comment]
Looks like the post was recorded without an id, it happens with other posts or just with this specific one?

**Comment by eurabilis** [comment]
All of them bruno, this bug is a duplicate of mine. I also havent been able to delete any content. https://github.com/quokkaproject/quokka/issues/179

**Comment by QiXuanWang** [comment]
Same here. Looks like MongoEngine not doing well? Or wrong/none Id passed to it?

**Comment by rochacbruno** [comment]
I am trying to fix this one! hope to fix today, seems to be a problem with changes in Flask Admin

**Comment by eurabilis** [comment]
Take your time you are doing good work here.

**Comment by QiXuanWang** [comment]
Where is the code that require attention? I could try it myself locally.

**Comment by rochacbruno** [comment]
CSRF problems in Quokka-Themes and new flask-admin that changed a lot! needs a complete ravamp. #201 is the issue for this problem

**Comment by rochacbruno** [comment]
```
pip uninstall flask-admin
pip install pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip
```

**Comment by blakev** [comment]
**requirements.txt**

``` bash
...
flask-admin=1.0.8
...
```

?

_edit: nevermind, it's not in pypi_

**Comment by rochacbruno** [comment]
yah, the Flask-Admin is on PyPi but not the older versions...
