### ISSUE TITLE
python manage.py createsuperuser

### ISSUE THREAD

**Issue by javalurker** [quokkaproject/quokka#19]
hi,i run command:
python manage.py createsuperuser

error information:
Traceback (most recent call last):
  File "manage.py", line 52, in <module>
    load_blueprint_commands(manager)
  File "D:\python_pro\flask_pro\quokka-env\quokka\quokka\ext\blueprints.py", lin
e 94, in load_blueprint_commands
    mod = imp.load_module(fname, f, filename, descr)
  File "D:\python_pro\flask_pro\quokka-env\quokka\quokka\modules\posts\commands.
py", line 4, in <module>
    from .models import Post
ValueError: Attempted relative import in non-package

i found that models.py(quokka/quokka/modules/posts) doesn't compile.

**Comment by rochacbruno** [comment]
Which Python version are you running?

**Comment by rochacbruno** [comment]
Hi @javalurker , I am not sure it is running really well in windows. So your help will be very appreciated to test it.

Can you please tell te version of Python and windows and Flask you are running?

Did you installed everything via `pip install -r requirements.txt` ?

tks

**Comment by javalurker** [comment]
hi,
i run 'pip install -r requirements.txt' command again.
it works very well. 
tks

**Comment by rochacbruno** [comment]
Thank you for helping with tests.
