### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by alexandre** [quokkaproject/quokka#192]
I"m not sure if is better reopen #164 or create one, the website is loading, but not working as a functional Quokka demo:

![demo_quokka](https://cloud.githubusercontent.com/assets/5252795/7515784/5cdaedb4-f4a0-11e4-87d9-9a60322ca678.png)

**Comment by jniltinho** [comment]
Hello Alexander,
Updated Server for Ubuntu 14.04, 
Because of this the demo is not active
The weekend will do deploy the Quokka and create an installation screencast and put on my Youtube channel -> https://www.youtube.com/channel/UCDbYk97RbOim_qhEshochpQ

:+1:

**Comment by alexandre** [comment]
@jniltinho,

Cool! 

(y)

**Comment by jniltinho** [comment]
@alexandre Demo QuokkaProject online !!!

Screencast (pt-BR)
http://youtu.be/G2AVa_QYeN4

Deploy QuokkaProject + ISPConfig Vhost + DigitalOcean + Ubuntu 
:+1:

**Comment by rochacbruno** [comment]
:+1:
