### ISSUE TITLE
Can quokka work with another Flask site?

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#195]
I mean I have a website running with Flask. Now I want quokka to be the CMS. What part should I modify? Didn't find details on your documents.

**Comment by rochacbruno** [comment]
Quokka is a full stack application, it is not developed to be used as a module in another Flask project (but it is a good idea which is planned for future versions).

The only way to have Quokka running together with your existing application is using DispatcherMiddleware, you will have two applications inside the same wsgi container. then, you route i.e: blog.yoursite.com to the quokka app and yoursite.com to you existing app.

**Comment by QiXuanWang** [comment]
That's what I guessed.
Appreciate your comment,  looking forward for your great work.
