### ISSUE TITLE
Docker Container support QuokkaProject

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#197]
Add new feature QuokkaProject Docker container

Docker support QuokkaProject

http://odewahn.github.io/docker-jumpstart/example.html
http://www.fullstackpython.com/docker.html
https://www.digitalocean.com/community/tutorials/docker-explained-how-to-containerize-python-web-applications

https://docs.docker.com/compose/django/
http://pythonclub.com.br/conteinerizando-suas-aplicacoes-django-com-docker-e-fig.html

**Comment by ellisonleao** [comment]
:+1:  for a Docker container and a Vagrant box as well.

**Comment by avelino** [comment]
+1

**Comment by rochacbruno** [comment]
:+1:

**Comment by rochacbruno** [comment]
Done!
