### ISSUE TITLE
httpie or curl

### ISSUE THREAD

**Issue by toliguo** [quokkaproject/quokka#198]
Could you please provide a CLI sample using httpie or curl to post the contents? Thanks.

**Comment by rochacbruno** [comment]
Sorry, the REST API #30 is not yet working, there is a issue ans it needs to be implemented

**Comment by toliguo** [comment]
Restful APIs are expected in the next version. Besides, do you have some recommendations on temporary solution if I want to use Python script to post some contents just like a content robot? Thanks.

**Comment by toliguo** [comment]
Restful APIs are expetected in the next version. Besides, do you have some recommendations as a temporary solution if I want to use Python scripts to post some contents continuously just like a content robot? Thanks.

**Comment by rochacbruno** [comment]
You can create the content directly in the database using a Python script and PyMongo/Mongoengine. Or you can mimic the POST that is made on admin page.

**Comment by toliguo** [comment]
I have checked with the admin page on admin/post, and set CSRF enabled = False in the settings.py. Would you please provide the sample to post an article if convinent? Thank you very much.

**Comment by rochacbruno** [comment]
Closing because there is another issue #30
