### ISSUE TITLE
can't get post published

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#199]
I've successfully added a post and it appears in "content->post" page. But the published column is negative. I tried to use "With selected" ->"Publish/Unpublish" to publish my new post, with the check box selected. Nothing happens. And "View on website" returns a 404. 
Any clue? 
BTW, when would be a doc available? I think I'll replace my old webpages with this one. But documentation is so eagerly required.

**Comment by rochacbruno** [comment]
If you click in the edit link and check the "publish" and save it should work, I will check if there is some bug in the publish action. There is no further documentation yet.

**Comment by QiXuanWang** [comment]
That solves the problem. But it seems this is the only way to publish a page. Shouldn't that "Publish/Unpublish" dropdown work too? Is it a bug or is it supposed to work like that?

**Comment by QiXuanWang** [comment]
I just tried all dropdowns for "With Selected" and it seems none of them functions. Is it not implemented yet?

**Comment by rochacbruno** [comment]
it is a bug, the dropdown should work!

**Comment by rochacbruno** [comment]
#201

**Comment by rochacbruno** [comment]
```
pip uninstall flask-admin
pip install pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip
```
