### ISSUE TITLE
strange large blank when loading post

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#200]
![quo_bug1](https://cloud.githubusercontent.com/assets/4425199/7579579/857606ae-f898-11e4-8fa9-58428f8a520e.PNG)
When click "read more" for homepage, it loads the whole post normally. But then there is a big blank between publish time and content. Then after a few seconds it goes back to normal again, the blank is gone. I doubt it's related to image loading. But I guess it's not a good thing. Please review.

Hopefully the attachment shows it correctly.

**Comment by rochacbruno** [comment]
I thionk it is a problem in template with social sharing buttons, will try to fix it

**Comment by rochacbruno** [comment]
Can you please update your flask-admin conforming instructions in  #201  and then, select the post in admin and click in "with selected --> export to json" and send me the json of your post. I could not reproduce the bug.

**Comment by QiXuanWang** [comment]
I still see this problem with the latest update. Here is the post:

[{"show_on_channel": true, "updated_at": {"$date": 1431374051688}, "contents": [{"created_at": {"$date": 1431287299165}, "updated_at": {"$date": 1431287299165}, "content": {"$oid": "55501873b4cf0420f9d1e3ae"}, "caption": "Girl", "purpose": {"$oid": "554c31a0b4cf046e66c49aec"}, "published": false, "identifier": "mainimage", "order": 1, "available_at": {"$date": 1431287299166}}], "title": "Hack Post Test", "available_until": {"$date": 1462909423000}, "created_by": {"$oid": "555011a0b4cf0420e3dcac8e"}, "content_format": "html", "comments_enabled": true, "channel": {"$oid": "554c3391b4cf046f5b60c00e"}, "available_at": {"$date": 1431287023000}, "body": "<p>&nbsp; So today I finnally make it works. Now I need to insert a picture</p>", "mpath": ",articles,technology,hack-post-test,", "tags": ["tech", ""], "related_channels": [], "long_slug": "articles/technology/hack-post-test", "last_updated_by": {"$oid": "555011a0b4cf0420e3dcac8e"}, "slug": "hack-post-test", "created_at": {"$date": 1431287299126}, "summary": "Test how it works and looks like", "values": [], "_cls": "Content.Post", "published": true, "model": "posts.post", "_id": {"$oid": "55501873b4cf0420f9d1e3ad"}}]
