### ISSUE TITLE
How to display original size picture?

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#206]
I can only have thumb-nail pictures showed in home page and in "Read more" view.
How can I let "Read more" view display original sized picture?

**Comment by rochacbruno** [comment]
You have to customize the default template here https://github.com/quokkaproject/quokka/blob/master/quokka/themes/default/templates/_helpers.html#L170 you can change the thumb=True to False.

Also you can use CSS to change the image size in here https://github.com/quokkaproject/quokka/blob/master/quokka/themes/default/static/css/main.css

**Comment by QiXuanWang** [comment]
Nice. It works perfectly! except for the blank :)
