### ISSUE TITLE
QuokkaProject style guide

### ISSUE THREAD

**Issue by alexandre** [quokkaproject/quokka#207]
I'm new here and IMHO it would be really useful. How the things work here? I send a PR or just push the code (if I have access for it)? Is there a rule about code coverage ? (e.g. min. percent, "don't decrease the coverage") should I create a branch to feature? and etc.

[ ]'s (hugs)

**Comment by rochacbruno** [comment]
@drgarcia1986 asked the same thing, now there is no contributing.md guides, but we can work on one! lets create the file and start collaboratively writing the rules.

**Comment by rochacbruno** [comment]
CONTRIBUTING.md file created! lets work on this, ideas?

**Comment by ellisonleao** [comment]
:+1: 

I think we can start with the cookiecutter contributing template 

https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/CONTRIBUTING.rst

**Comment by drgarcia1986** [comment]
:+1:

**Comment by alexandre** [comment]
:+1: 

@rochacbruno , should we close this issue offer/discuss ideas by pull requests?

**Comment by rochacbruno** [comment]
Yes @alexandre good idea, feel free to edit CONTRIBUTING.md and send the PR, but we will close this issue only when the PR is accepted

**Comment by alexandre** [comment]
great, @rochacbruno! [vegan] :cake:
