### ISSUE TITLE
Question of Admin->Accounts->Roles

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#208]
I see you have 5 roles written there. But when I use "Edit record", it pops some description view. What should I do with it? Add some description? How can I control the actual access permissions, I mean from that Admin page?

I found those description in core/admin/views.py. But I'm still confused about those terminology "Channel", "Subcontent", "config", "Link". Do you have documentation? Or is reading the code only way to understand that? Forgive my innocent if it's simple question.

**Comment by rochacbruno** [comment]
All the extra roles was dropped from popualte, by default only "admin" and "author" will be created.

All rule system will be soon documented
