### ISSUE TITLE
In hopes of getting myself rid of #204 Im doing a complete reinstall now getting "ImportError: No module named PyRSS2Gen"

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#211]
In hopes of getting myself rid of #204 Im doing a complete reinstall now getting "ImportError: No module named PyRSS2Gen"

But I have the module installed. Can I get a hand thanks.

Traceback (most recent call last):
  File "./wsgi.py", line 8, in <module>
    application = DispatcherMiddleware(create_app(), {
  File "./quokka/**init**.py", line 48, in create_app
    from .ext import configure_extensions
  File "./quokka/ext/**init**.py", line 13, in <module>
    from . import (generic, babel, blueprints, error_handlers, context_processor
s,
  File "./quokka/ext/views.py", line 6, in <module>
    from quokka.core.views import ContentDetail, ContentList, TagList
  File "./quokka/core/views.py", line 6, in <module>
    import PyRSS2Gen as pyrss
ImportError: No module named PyRSS2Gen
Tue Jun  2 15:19:07 2015 - unable to load app 0 (mountpoint='') (callable not fo
und or import error)

(venv)root@sid:/var/log/uwsgi/app# pip install  PyRSS2Gen
Requirement already satisfied (use --upgrade to upgrade): PyRSS2Gen in /usr/locl/lib/python2.7/dist-packages
(venv)root@sid:/var/log/uwsgi/app#

**Comment by rochacbruno** [comment]
Strange because this is in requirements https://github.com/quokkaproject/quokka/blob/master/requirements.txt#L38

do a 

```
pip install PyRSS2Gen
```

**Comment by eurabilis** [comment]
Thats the thing I have it installed, see my check for it above at my command line. I tried --upgrade as well it just says its already installed. I tried both installing it for the base system and the virtualenv.

**Comment by blakev** [comment]
This was mine...I will look into this today.

**Comment by eurabilis** [comment]
Thank you

**Comment by blakev** [comment]
What version of linux are you using? What's the output of header when executing `python`, aka: 

``` bash
Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by eurabilis** [comment]
I am using Debian Jesse completely up to date and python says 2.7.9 with
GCC 4.9.2 on linux2 thanks

**Comment by rochacbruno** [comment]
If it is a problem, we can do a **graceful degratation** in the same way we dis for weasyprint.

```
try:
    import PyRSS2Gen
except ImportError:
   PyRSS2Gen = SOME_DEFAULT
   rss_views_disabled = True
```

then, we disable RSS if the module cannot be imported

**Comment by eurabilis** [comment]
Thanks bruno. I am still learning to code and am not as advanced as you guys. That said what do I change SOME_DEFAULT to, and what file can I find this code?

**Comment by rochacbruno** [comment]
Dont worry @eurabilis this has to be done in the core/views and SOME_DEFAULT was just an example, maybe it will be needed to have some dummy class. I can handle it, but maybe @blakev can do it faster because he implemented the RSS feature

**Comment by blakev** [comment]
Yeah, I will clean it up -- as well as the PDF feature needs some revamping. I tried to duplicate it from a fresh environment in Debian, but it worked like it should, so my only suggestion is that you're installing and running Quokka from two different pips, ala `sudo pip install` and `pip install`

Other than that I have no idea why it wouldn't work :/

**Comment by eurabilis** [comment]
Yup you were right pip was installing to the global system. I have fixed the problem and its all better now, thanks for showing me the light.
