### ISSUE TITLE
post view problem

### ISSUE THREAD

**Issue by netqyq** [quokkaproject/quokka#213]
when I read the default a post, such as "This is a Blog Post", the content of the page will jump to the botton of the page. the middle position of page is blank

![image](https://cloud.githubusercontent.com/assets/3492992/8022409/3394aeca-0d02-11e5-9ee2-407c103b736c.png)

![image](https://cloud.githubusercontent.com/assets/3492992/8022416/a42ea46a-0d02-11e5-8a31-41d8c3fbe2fd.png)

**Comment by rochacbruno** [comment]
I've heard the same problem before, I guess this is a problem with browser version and CSS or maybe one of the sharing plugin.

Please tell me:

O.S version, Browser version

**Comment by netqyq** [comment]
os windows 7
chrome 41.0.2272.101 (64-bit)
firefox 38.0.5

chrome and firefox both match this issue.

**Comment by rochacbruno** [comment]
Fixed in last commit
