### ISSUE TITLE
start error ,cannot load library 'libcairo.so.2 ,Error importing flask-weasyprint!

### ISSUE THREAD

**Issue by netqyq** [quokkaproject/quokka#214]
# python manage.py run0

```
Error importing flask-weasyprint!
PDF support is temporarily disabled.
Manual dependencies may need to be installed.
See,
    `http://weasyprint.org/docs/install/#by-platform`_
    `https://github.com/Kozea/WeasyPrint/issues/79`_

cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
```

2015-06-16T05:57:21.702+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40963 #9 (1 connection now open)
/data/quokka_venv/lib/python2.7/site-packages/flask_script/**init**.py:153: UserWarning: Options will be ignored.
  warnings.warn("Options will be ignored.")
- Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
- Restarting with stat
  
  Error importing flask-weasyprint!
  PDF support is temporarily disabled.
  Manual dependencies may need to be installed.
  See,
      `http://weasyprint.org/docs/install/#by-platform`_
      `https://github.com/Kozea/WeasyPrint/issues/79`_
  
  cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
  2015-06-16T05:57:22.383+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40964 #10 (2 connections now open)
  /data/quokka_venv/lib/python2.7/site-packages/flask_script/**init**.py:153: UserWarning: Options will be ignored.
  warnings.warn("Options will be ignored.")

**Comment by rochacbruno** [comment]
Weasyprint will be dropped in favor od PDFkit
