### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by victorwestmann** [quokkaproject/quokka#215]
Hi there. 

I met this project in an event this past weekend. I'm interested to join the project but I'm willing to learn. I don't have (yet) enough coding skills (even though I can code _some_ python). Where should I start? Thanks!

**Comment by alexandre** [comment]
Hi and welcome, @victorwestmann. =]

I think the wiki is a good start point, there is a lot of information there. I think you already read the contributing[0] doc, right? We have a gitter.im[1] channel too

0 - https://github.com/quokkaproject/quokka/blob/master/CONTRIBUTING.md
1 - https://gitter.im/quokkaproject/quokka

[ ]'s (hugs)

**Comment by drgarcia1986** [comment]
Welcome @victorwestmann :smile: 

A good start is try to running project in your machine and try to running tests.

[]'s

**Comment by rochacbruno** [comment]
Welcome @victorwestmann there is a roadmap file https://github.com/quokkaproject/quokka/blob/master/roadmap.md with some prioritized issues.

**Comment by victorwestmann** [comment]
Thanks!
