### ISSUE TITLE
is it have a feature in admin panel that can hide the dorp down button? 

### ISSUE THREAD

**Issue by netqyq** [quokkaproject/quokka#217]
Hi there:
is it have a feature in admin panel that can hide or close the dorp down button? 

thank you !

![image](https://cloud.githubusercontent.com/assets/3492992/8200534/c82ec536-14f8-11e5-844f-cd239ebfc332.png)

**Comment by rochacbruno** [comment]
I cant reproduce this bug, for me in I.E, FF and Chrome the dropdown is hiding on lose focus.

**Comment by rochacbruno** [comment]
Versions of bootstrap got updated, fixed this problem in I.E
