### ISSUE TITLE
Python 2.6 compatibility

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#22]
- Check zero-length in format() replacing `"{} {}".format(x, y)` with `"{0} {1}".format(x, y)`
- Check the instalation of `importlib`, include in requirements2.6.txt
- Check the from **future** import absolute_import

**Comment by ellisonleao** [comment]
Already started here:

https://github.com/pythonhub/quokka/commit/8798666dceba74b58983528b4bc898e69a0dacba

I'm using a [py2.6] identification for future filters or something

**Comment by rochacbruno** [comment]
Closing, for now Quokka will only support Python 2.7. Python 3.x will be added in future when MongoEngine and other libraries updates.
