### ISSUE TITLE
Quokka quickstart is returning error

### ISSUE THREAD

**Issue by matheusbrat** [quokkaproject/quokka#220]
I think this error is related to requirements file which does not specify the mongoengine version neither the flask-mongoengine

my pip freeze (I'm using a virtualenv, so all packages are installed from quokka)

```
awesome-slugify==1.6.5
Babel==1.3
blinker==1.3
dealer==2.0.4
flake8==2.4.1
Flask==0.10.1
Flask-Admin==1.0.8
Flask-Assets==0.10
Flask-Babel==0.9
Flask-BabelEx==0.9.2
Flask-Cache==0.13.1
Flask-Collect==1.2.1
Flask-DebugToolbar==0.10.0
Flask-Gravatar==0.4.2
Flask-HTMLBuilder==0.10
Flask-Login==0.2.6
Flask-Mail==0.9.1
Flask-Mistune==0.1.1
flask-mongoengine==0.7.1
Flask-OAuthlib==0.9.1
Flask-Principal==0.4.0
Flask-Script==2.0.5
Flask-Security==1.7.4
Flask-Testing==0.4.2
Flask-WTF==0.11
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
mccabe==0.3.1
mistune==0.6
mongoengine==0.10.0
nose==1.3.7
oauthlib==0.7.2
passlib==1.6.2
pep8==1.5.7
Pillow==2.8.2
pyflakes==0.8.1
pymongo==2.7.1
PyRSS2Gen==1.1
pytz==2015.4
PyYAML==3.11
Quokka-Themes==0.1.2
regex==2015.6.21
requests==2.7.0
requests-oauthlib==0.5.0
simplejson==3.7.3
speaklater==1.3
twill==1.8.0
Unidecode==0.4.18
webassets==0.10.1
Werkzeug==0.10.4
wheel==0.24.0
WTForms==1.0.5
```

python manage.py populate

```
Error importing flask-weasyprint!
PDF support is temporarily disabled.
Manual dependencies may need to be installed.
See,
    `http://weasyprint.org/docs/install/#by-platform`_
    `https://github.com/Kozea/WeasyPrint/issues/79`_

No module named flask_weasyprint
```

Loading fixtures
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    app = create_app()
  File "/Users/CKL/han/quokka/quokka/quokka/**init**.py", line 49, in create_app
    configure_extensions(app, admin_instance or admin)
  File "/Users/CKL/han/quokka/quokka/quokka/ext/**init**.py", line 31, in configure_extensions
    fixtures.configure(app, db)
  File "/Users/CKL/han/quokka/quokka/quokka/ext/fixtures.py", line 18, in configure
    populate.create_purposes()
  File "/Users/CKL/han/quokka/quokka/quokka/utils/populate.py", line 175, in create_purposes
    self.create_purpose(purpose)
  File "/Users/CKL/han/quokka/quokka/quokka/utils/populate.py", line 162, in create_purpose
    purpose, created = SubContentPurpose.objects.get_or_create(
AttributeError: 'BaseQuerySet' object has no attribute 'get_or_create'

**Comment by matheusbrat** [comment]
+- Removed get_or_create() deprecated since 0.8.0. #300

https://github.com/MongoEngine/mongoengine/blob/master/docs/changelog.rst

**Comment by rochacbruno** [comment]
Yeah, I knew about it, we need to pin the mongoengine and flask-mongoengine versions til we make the needed changes

**Comment by rochacbruno** [comment]
```
flask-mongoengine==0.7.1
mongoengine==0.9.0
pymongo==2.7.1
```

**Comment by rochacbruno** [comment]
Thanks @x-warrior I guess it is now fixed
