### ISSUE TITLE
Python 3 support is not ok

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#222]
Running with Python3.x still raises a lot of erros, some of them below:
- [ ] It misses pep8 and pyflakes packages (should add to requirements)
- [ ] flaskhtmlbuilder uses unicode() and it does not exists in py3, lead in to an error in admin

**Comment by alexandre** [comment]
I'll try to work on it today.

**Comment by rochacbruno** [comment]
:+1:

**Comment by alexandre** [comment]
@rochacbruno , about pep8 and pyflakes: should it be already installed when we install the requirements_test deps, shouldn't?

``` shell
(quokka-py3)➜  quokka-py3 git:(master) cat requirements_test.txt|grep flake8
flake8
```

**Comment by ellisonleao** [comment]
`flake8` does the job because its a wrapper around pep8 and pyflakes. i believe we don't need `pyflakes`.

**Comment by alexandre** [comment]
I'm trying to collaborate with this issue again...

@rochacbruno can you update this issue with other errors? I have opened a pull request in the flaskhtmlbuilder repo. to fix those problems.

**Comment by mikeyhew** [comment]
I'm evaluating quoakka for future use right now, and would consider helping port it to python 3 rather than developing my own system. What still needs to be done to make it work in python 3.5?

**Comment by alexandre** [comment]
@mikeyhew ,

You can run an local instance of Quokka using Python 3.5 and to report (or fix =P) compatibility issues.
My first effort was add an initial support to every repository in the quokkaproject org.

What I think that are our next steps:
- [ ] Ensure that every dep in `requirements.txt` supports python3
- [ ] _Seek and Fix_  incompatible code in the quokka codebase
- [ ] Encourage people to use python3 and report issues. =]
