### ISSUE TITLE
Script being included on themes/cosmo is the wrong one.

### ISSUE THREAD

**Issue by matheusbrat** [quokkaproject/quokka#224]
/quokka/themes/cosmo/templates/admin/actions.html

`<script src="{{ admin_static.url(filename='admin/js/actions.js') }}"></script>`

This url is translated to: http://127.0.0.1:5000/admin/static/admin/js/actions.js

Which loads correctly but changing the file /quokka/themes/cosmo/static/admin/js/actions.js I can't see my changes. It seems that this file is coming from flask-admin /venv/lib/python2.7/site-packages/flask_admin/static/admin/js/actions.js because when I change it, I see my changes.

Changing actions.html

`<script src="{{ admin_static.url(filename='admin/js/actions.js') }}"></script>`

For

`<script src="{{theme_static('admin/js/actions.js')}}"></script>`

Seems to solve the problem. 

``````
aniso8601==1.0.0
awesome-slugify==1.6.5
Babel==1.3
blinker==1.3
dealer==2.0.4
ecdsa==0.13
Fabric==1.10.2
flake8==2.4.1
Flask==0.10.1
Flask-Admin==1.0.8
Flask-Assets==0.10
Flask-Babel==0.9
Flask-BabelEx==0.9.2
Flask-Cache==0.13.1
Flask-Collect==1.2.1
Flask-DebugToolbar==0.10.0
Flask-Gravatar==0.4.2
Flask-HTMLBuilder==0.10
Flask-Login==0.2.6
Flask-Mail==0.9.1
Flask-Mistune==0.1.1
flask-mongoengine==0.7.1
Flask-OAuthlib==0.9.1
Flask-Principal==0.4.0
Flask-RESTful==0.3.3
Flask-Script==2.0.5
Flask-Security==1.7.4
Flask-Testing==0.4.2
Flask-WTF==0.11
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
mccabe==0.3.1
mistune==0.6
mongoengine==0.9.0
nose==1.3.7
oauthlib==0.7.2
paramiko==1.15.2
passlib==1.6.2
pep8==1.5.7
Pillow==2.8.2
pycrypto==2.6.1
pyflakes==0.8.1
pymongo==2.7.1
PyRSS2Gen==1.1
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
Quokka-Themes==0.1.2
regex==2015.6.24
requests==2.7.0
requests-oauthlib==0.5.0
simplejson==3.7.3
six==1.9.0
speaklater==1.3
twill==1.8.0
Unidecode==0.4.18
webassets==0.10.1
Werkzeug==0.10.4
wheel==0.24.0
WTForms==1.0.5```
``````

**Comment by rochacbruno** [comment]
:+1:  nice! Are you going to send a PR or prefer that I change it here?

**Comment by matheusbrat** [comment]
I'm sending a pull request.
