### ISSUE TITLE
add meta tags for embedding

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#226]
Following the example below

http://iframely.com/debug?uri=http%3A%2F%2Ftechcrunch.com%2F2015%2F07%2F07%2Fcitibank-is-working-on-its-own-digital-currency-citicoin%2F

Add all needed meta tags and its administration page on pure_theme

**Comment by ellisonleao** [comment]
We could add twitter cards as well

https://dev.twitter.com/cards/types/summary-large-image

**Comment by rochacbruno** [comment]
:+1: 

Currently it is being done at template, not nice.. we can have a feature for activating this in admin and use only {{ social_meta_tags }} to include it in templates. 

(the same way is being done at https://github.com/citruspi/Flask-Analytics)

**Comment by rochacbruno** [comment]
dont forget the author_badge with image (like the one used by EXAME page on facebook)
