### ISSUE TITLE
Material Theme

### ISSUE THREAD

**Issue by ellisonleao** [quokkaproject/quokka#228]
http://www.getmdl.io/

**Comment by rochacbruno** [comment]
Created a repository https://github.com/quokkaproject/theme_material

Now we need to copy the pure_theme structure https://github.com/quokkaproject/quokka/tree/pure_theme/quokka/themes/pure and implement material design

**Comment by ellisonleao** [comment]
:+1:  i will take a look at that.

**Comment by rochacbruno** [comment]
After that we will need to create a theme_installation tool

```
quokka-installer install theme material
```

and then, it will download the theme on to /themes folder

**Comment by rochacbruno** [comment]
closing because the theme is already being developed in another repository
