### ISSUE TITLE
flask-admin didn't register Channel

### ISSUE THREAD

**Issue by javalurker** [quokkaproject/quokka#23]
information:
15.08 17:10:56 root         WARNING  admin.register(<\class 'quokka.core.models.C
hannel'>, <class 'quokka.core.models.ChannelAdmin'>, (), {'category': 'Content'}
) error: 'NoneType' object has no attribute 'get'

---

i updated code in 'quokka/core/models.py'.
now,it works !

old version:
class ChannelAdmin(ModelAdmin):
    roles_accepted = ('admin', 'editor')
    column_list = ('title', 'long_slug', 'is_homepage', 'published')
    column_filters = ['published', 'is_homepage', 'include_in_rss',
                      'show_in_menu', 'indexable']
    column_searchable_list = ('title', 'description')
    form_columns = ['title', 'slug', 'description', 'parent', 'is_homepage',
                    'include_in_rss', 'indexable', 'show_in_menu', 'order',
                    'published', 'canonical_url', 'values']

new version:
class ChannelAdmin(ModelAdmin):
    roles_accepted = ('admin', 'editor')
    column_list = ('title', 'long_slug', 'is_homepage', 'published')
    column_filters = ['published', 'is_homepage', 'include_in_rss',
                      'show_in_menu', 'indexable']
    column_searchable_list = ('title', 'description')
    form_columns = ['title', 'slug', 'description', 'parent', 'is_homepage',
                    'include_in_rss', 'indexable', 'show_in_menu', 'order',
                    'published', 'canonical_url']

**Comment by javalurker** [comment]
flask-admin didn't register Config

the same problem.

**Comment by rochacbruno** [comment]
I cannot reproduce the error here, Just instaled in a fresh Vm and worked ok.

Are you using an existing database? can you try with a newclean database? so I can figure out if it is a problem of corrupted data.

**Comment by javalurker** [comment]
i cleaned Vm and db,
but it didn't work because Config inherit HasCustomValue.
the problem at:

class HasCustomValue(object):
    values = db.ListField(db.EmbeddedDocumentField(CustomValue)) #problem!

---

why?

windows7 64bit,python 2.7.3,

**Comment by rochacbruno** [comment]
It was a problem in mrjoes/flask-admin I sent a pull request and solved in Quokka admin core.. thanks
