### ISSUE TITLE
Optional cache for template rendering 

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#243]
use redis

**Comment by abnerpc** [comment]
@rochacbruno can you elaborate a little more about this one ? How you think it could work ?

**Comment by ellisonleao** [comment]
I believe we can create some set of methods/decorators to record a a key/value of a rendered template using redis as the backend.

Are we caching only the context variables or the whole template rendered?

**Comment by rochacbruno** [comment]
@abnerpc @ellisonleao Flask-cache is already installed in project, and it exposes some backends as Memcached and Redis.

We only need to implement it, and figure out how to implement.

The caching levels should be configurable in settings so we can choose levels
'DATABASE', 'VIEW', 'RENDERING', 'RESPONSE'
1. cache database access
   When cache level is **DATABASE** Quokka will cache objects such as Channel and Content, the manager **objects** and its methods should look to the cache before it goes to MongoDB.
2. Cache view
   In the core.views there ContentList and ContentDetail, those views does some operations as accessing database, applying some filtering such as permission filtering, and also those views uses the **get_template_names** in order to choose the active theme and the desired template which is variable. when cache level is **VIEW** the whole view output should be cached. But the user.id should be used to create the cache key because content access can vary between users. (use the same for anonimous user). so the only thing that will be done in run-time is template rendering.
3. Cache rendering 
   template rendering is done by quokka_themes.render_template, given a URL and a Context it can look to the cache to get a response.
4. Cache response
   Flask does some things in response, add extra headers etc.. we can cache the entire response.

All those cache levels can be combined together, if settings.CACHE_LEVELS = ('DATABASE', 'VIEW') template rendering and response will be done at run-time (useful for mobile swtiching for example)

# cache invalidation

Content and Channel should have a hook in its **save** method, since it is modified the cache should be invalidated for the changes to be reflected.

Flask-Cache already has a TTL parameter
