### ISSUE TITLE
URL shortener integration

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#254]

**Comment by ellisonleao** [comment]
Maybe we can use https://github.com/ellisonleao/pyshorteners . It's not 100% but there are a lot of shorterners available

**Comment by rochacbruno** [comment]
:+1: 

The idea is:
- if SHORTENER_ENABLED = True
- SHORTENER_SETTINGS = {"apikey": "dfsdfsdf", ....}
- After Content.save() (last step) the content.get_http_url() will be shortened
- If there is a Celery enabled (not yet available) the shortnening will be done using celery, else it will be done sync.
- Once shortened the short URL will be saved in content itself and will be available in admin list

@felipevolpone

**Comment by ellisonleao** [comment]
If we use that lib we Can have multiple shorteners integration (bit.ly,
googl.gl, senta.la, etc)

Em sáb, 18 de jul de 2015 22:22, Bruno Rocha notifications@github.com
escreveu:

**Comment by felipevolpone** [comment]
Great guys! 
Initially I'll do just with bit.ly (keep in mind an MVP of feature). We can plan to others integrations in the future.

**Comment by felipevolpone** [comment]
Because of this [problem/issue](https://github.com/ellisonleao/pyshorteners/issues/25) at the lib I didn't use Bit.ly, I used Tinyurl. It's done. In the admin post list I didn't make shortener_url a link, someone thinks that is necessary?

**Comment by rochacbruno** [comment]
:+1: greate work @felipevolpone 

I just made some changes on settings, settings should not be directly get from 'from quokka import settings' because there is some settings on local_settings and also in database and they should be used.

So there is lazy_setting for this (not perfect yet because it fails in some usecases)

Now we need to find a way to make 'short_url' to be hidden from admin post list when SHORTENER_ENABLED = False.

**Comment by felipevolpone** [comment]
thanks @rochacbruno !
You're right, so I'll work on it.

**Comment by rochacbruno** [comment]
nice @felipevolpone 

Its not so trivial to get the setting variable in ModelAdmin context, I tried but will need the changes of #274

**Comment by ellisonleao** [comment]
Nice, i will try to keep the pyshorteners lib updated. There are some issues ongoing now, but so far its working.

**Comment by ellisonleao** [comment]
I will have to update some shorteners with the latest APIs and some of them are now requiring OAuth2 authentication, so we will need to make some documentation about that or use a simple shortener, like tinyurl for now.

**Comment by rochacbruno** [comment]
@ellisonleao we should use the simpler one (tinyurl) for default, and have some documentaion on how to change for bit.ly

**Comment by felipevolpone** [comment]
Good idea, I'll change README to cover this feature too.

**Comment by ellisonleao** [comment]
:+1:  i will add some proper docs on http://github.com/ellisonleao/pyshorteners as well.

**Comment by rochacbruno** [comment]
also we should change this line

https://github.com/quokkaproject/quokka/blob/a8cd3cce59fdcb5b9ec206819d7a6c3805066abb/quokka/settings.py#L277

from

```
SHORTENER_DEFAULT_API = 'TinyurlShortener'
```

to

```
SHORTENER_CONFIG = {
    'name': 'TinyurlShortener',
}
```

then allowing

```
SHORTENER_CONFIG = {
    'name': 'BitlyShortener',
    'api_key': ....,
    'another-arg': ....
}
```

So in utils.shorturl.py https://github.com/quokkaproject/quokka/blob/development/quokka/utils/shorturl.py#L16

```
 self._shortener = Shortener(shortener_name, **shortener_config)
```

in

```
class ShorterURL(object):

    _shortener = None

    @property
    def shortener(self):
        if not self._shortener:
            shortener_config = lazy_setting('SHORTENER_CONFIG')
            shortener_name = shortener_config.pop('shortener_name')
            self._shortener = Shortener(shortener_name, **shortener_config)
        return self._shortener

    def short(self, url):
        return self.shortener.short(url)
```

or something like that

but it also depends on #274

**Comment by felipevolpone** [comment]
I don't want to go against the idea, but I think that we could keep things as simple as it could be. I don't see why it would be good have more than just one shorter url api. So, in my opinion settings.py could stay that way, to keep it simple. If in future we want to add another API to shorter urls, we can change the code, but just when the change is necessary.
I just want that we keep focused on what is really important to the MVP of project.

What do you think guys?

**Comment by rochacbruno** [comment]
I agree to keep only TinyUrl working for now, but the goal is Bit.Ly because it is one of the best services, and also, implemeting its support was inspired by the current use of bit.ly in publishing area. Bit,ly gives some nice analytics reports.

TinyURL is only a shortener, it does not add any value in terms of analytics. Bit.ly, Ow.ly and others has analytics features and would be better option.

For config as almost every service will need more configuration such as api_key it is better to specify the config format now than when it goes to the master, so in the future the settings will be still compatible.

**Comment by felipevolpone** [comment]
Oh ok, I didn't knew it of all these advantages. So, I complete agree with you. Btw, change the config of shorter to a dict is nice so.

**Comment by ellisonleao** [comment]
The lib has ow.ly integration too. I am working now to update the bit.ly API and use the latest. Will check the ow.ly and goo.gl as well.

**Comment by ellisonleao** [comment]
Bit.ly is now working on pyshorteners==0.4.1

you will need to pass a `bitly_login`  `bitly_api_key` and a `bitly_token` (access_token) in order to expand/short urls. Analytics will come soon.

**Comment by felipevolpone** [comment]
Thank you @ellisonleao. Tomorrow I change to use bit.ly

**Comment by ellisonleao** [comment]
If anything goes wrong please let me know.

**Comment by rochacbruno** [comment]
@felipevolpone fixed the admin column, I implemented #274 and added a condition to show short_url field only if shortener is enabled

**Comment by felipevolpone** [comment]
@rochacbruno great! I'll work on documentation and the change to bit.ly

**Comment by ellisonleao** [comment]
I just remembered that we could add the qrcode image on the post as well if we want. The lib provides a `qrcode` method that prints the qrcode image. What do you guys think? Example on a bit.ly image

http://chart.apis.google.com/chart?cht=qr&chl=http://bit.ly/1JDsAed&chs=120x120

![](http://chart.apis.google.com/chart?cht=qr&chl=http://bit.ly/1JDsAed&chs=120x120)

**Comment by felipevolpone** [comment]
Sorry for delay, but it's finally done. Also, I changed README to document it.
