### ISSUE TITLE
authors can choose if picture comes from gravatar, local or another url

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#255]

**Comment by felipevolpone** [comment]
The concept of author is the same of user? Cause I didn't find any place to create or view authors. 
If is the same, this integration should happen in the creation of a new user, right?

**Comment by rochacbruno** [comment]
Author is a common registered user, the difference is that they have 'admin' or 'author' role, so they appear on the page http://development.quokkaproject.org/authors/

https://github.com/quokkaproject/quokka/blob/development/quokka/modules/authors/utils.py#L38

Authors module is in: https://github.com/quokkaproject/quokka/tree/development/quokka/modules/authors

So we need to create a new view in this module, in this view we need to have the option for users/authors to edit his profile including a picture and choosing between gravatar, url for image or upload a new image.
