### ISSUE TITLE
Menu at the homepage is not so friendly

### ISSUE THREAD

**Issue by felipevolpone** [quokkaproject/quokka#257]
The main menu at the top of page is a little bit strange. The background of page is white and the background of menu is white too. Check out the screenshot.

![captura de tela 2015-07-15 as 00 25 18](https://cloud.githubusercontent.com/assets/1590527/8690252/539e7220-2a88-11e5-9515-f4df6833bef9.png)

**Comment by rochacbruno** [comment]
css issue, need help
