### ISSUE TITLE
Babel Problem 

### ISSUE THREAD

**Issue by realli** [quokkaproject/quokka#261]
I think there may be problem when we import `_` and `_l` from quokka.core.admin, for example, in the file `modules/posts/admin.py`, 

```
admin.register(Post, PostAdmin, category=_("Content"), name=_l("Post"))
```

both `_` and `_l` are imported from `quokka.core.admin`, and they are refer to `gettext` and `lazy_gettext` in the module `flask.ext.admin.babel`, in which `flask_admin` create a new `Domain` called `CustomDomain` to handle translation. So both `"Content"` and `"Post"` will be translated according to `flask_admin`'s translations  directory which obviously doesn't contain any information about `"Content"` and `"Post"`.

I think we should handle this kind of translation in the quokka scope, not to rely on `flask_admin`'s `Domain`. And by the way, the category should also use `lazy_gettext`, using `_` will not work.

Check the Screenshot I made, in which I change the Accounts to use another `Domain`, but keep other entries using `flask_admin`'s `Domain`:
![2015-07-17 10 04 42](https://cloud.githubusercontent.com/assets/3313107/8739214/8344e61e-2c6b-11e5-8575-3496985e4d51.png)

**Comment by rochacbruno** [comment]
good catch @realli do you have a hint on how to fix this problem or maybe can you send a PR? 

@mrjoes have said something about it in a Flask Admin related issue, still nees to find a way to use lazy gettext.

**Comment by realli** [comment]
@rochacbruno , I would love to help. In my opinion, we can create a new `Domain` in app scope, and then we can use the `gettext` and other function in our `Domain` to perform our custom translations. And leave the `flask_admin`'s `Domain` to deal with its own translation.

**Comment by rochacbruno** [comment]
👍

**Comment by wangyishuai007** [comment]
@realli 请教下这个Po文件改怎么用？google出来的我都看不懂，谢谢~

**Comment by realli** [comment]
@wangyishuai007 , http://translations.readthedocs.org/en/latest/flask-babel.html,  可以看看这个
