### ISSUE TITLE
Feature Request -- module agregetor blogs

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#268]
Module like Python Planet
Add module planet agregetor blogs

Libs:
Python Planet 2.0
http://www.planetplanet.org/
https://people.gnome.org/~jdub/bzr/planet/2.0/

Get feed rss convert to json and import into MongoDB

**Comment by rochacbruno** [comment]
Nice! it should be easy to develop, using rssparser, xmltodict, atomparser and methods already included in utils.populate

**Comment by andrelramos** [comment]
I'm working in this.

Follow the module repo:
https://github.com/andrelramos/quokka-RSSaggregator
