### ISSUE TITLE
Filter problem at the post list admin page

### ISSUE THREAD

**Issue by felipevolpone** [quokkaproject/quokka#270]
These options of filter: Title, Summary, Created At, Available At aren't  working well. The first time that page is loaded and some filter is added, the filter wasn't work.

**Comment by rochacbruno** [comment]
![content post quokka admin](https://cloud.githubusercontent.com/assets/458654/8769459/255cdfba-2e74-11e5-8cc7-55e9716c8602.png)

On the first time it loads, it showed a blank text input, then I used 0 for False and 1 for True, so it started showing the select with options.

**Comment by felipevolpone** [comment]
This was fixed [here](https://github.com/quokkaproject/quokka/issues/246) by [this commit](https://github.com/quokkaproject/quokka/commit/de09e09e1cbde68160bf6f5fdc3ad4f3b6070c2d). This issue it's about all filters except Published/Unpublished actually, 'cause they wasn't working very well.

I changed the description of this issue to be clearer.
