### ISSUE TITLE
Commands needs a namespace

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#277]
Currently commands are being loaded direclty, i.e:

```
# comes from quokka core
python manage.py shell
python  manage.py populate
python manage.py runserver

# comes from accounts module
python manage.py createuser

# comes from medias module
python manage.py listmedias

# comes from cart third party module
python manage.py clearemptycarts
```

If two modules defines a command with similar names there will be a conflict.

It needs to be defined with a namespace using a dot "." or an underline "_"

```
# NO CHANGES cuse it comes from quokka core
python manage.py shell
python  manage.py populate
python manage.py runserver


# add namespace
# comes from accounts module
python manage.py accounts.createuser
or
python manage.py accounts_createuser

# comes from medias module
python manage.py medias.listmedias

# comes from cart third party module
python manage.py cart.clearemptycarts
```

**Comment by rochacbruno** [comment]
Do you thing it is possible @abnerpc ?
also we need to decide about the **cmd_** prefix on commands, is it needed?

**Comment by abnercampanha-luizalabs** [comment]
@rochacbruno yeap... I'm on it ;)...
about the `cmd_` prefix I just used like click complex [example](https://github.com/mitsuhiko/click/tree/master/examples/complex), but we don't actually need it...

**Comment by abnerpc** [comment]
@rochacbruno yeap... I'm on it ;)...
about the cmd_ prefix I just used like click complex example, but we don't actually need it...

**Comment by rochacbruno** [comment]
Done by @abnerpc :+1:
