### ISSUE TITLE
Rewrite tests with PyTest

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#281]
With pytest it is easy to create a single app context for testing, so we should get rid of nose and unitests and use pytest

**Comment by ellisonleao** [comment]
:+1: changed all tests on pyshorteners to pytest and it was awesome!

**Comment by lerrua** [comment]
+1

**Comment by ellisonleao** [comment]
are we using https://pypi.python.org/pypi/pytest-flask ?

**Comment by rochacbruno** [comment]
:+1: we can try this extension

**Comment by rochacbruno** [comment]
Assuming this is closed! pytest is being used to new tests, old ones can be migrated in the future.

**Comment by ellisonleao** [comment]
:+1:
