### ISSUE TITLE
Replace internal commenting system and use as default instead of disqus

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#282]
Started a new project to handle comments https://github.com/rochacbruno/flasqus

Quokka internal comments should be the default again but using this Flasqus solution when its ready.

Disqus, Intensedebate and facebook will still be an option but not configured by default.

**Comment by QiXuanWang** [comment]
So this is fixed? I didn't find this feature with a latest clone though. Any idea how to enable this flasqus?
The issue is that I tried to change disqus to internal in Admin->Settings->Config but it won't save the internal value and kept discus...

**Comment by rochacbruno** [comment]
Not yet, we need to finish that implementation.
