### ISSUE TITLE
Why register a blueprint in case of conflic?

### ISSUE THREAD

**Issue by rturk** [quokkaproject/quokka#284]
I'm having a hard time trying to understand why quokka/quokka/ext/blueprints.py will register a duplicated  Blueprint? This could be hell in case circular imports. 

```
if blueprint.name not in app.blueprints:
    app.register_blueprint(blueprint)
else:
    blueprint.name += str(random.getrandbits(8))
    app.register_blueprint(blueprint)
    logger.warning("CONFLICT:%s already registered, using %s",fname,blueprint.name)
```

Why the second register "app.register_blueprint(blueprint)" in the else block? Shouldn't be nothing since Blueprint is already registered?

**Comment by rochacbruno** [comment]
This was done because of a problem in flask-admin, once we move to the new Flask_admin this can be removed.  also there will be #151

**Comment by rochacbruno** [comment]
Fixed!!! implemented namespaces for blueprints and urls. no more conflicts
