### ISSUE TITLE
Create material design theme

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#285]
Material Design Theme is being created at quokkaproject/theme_material repository

**Comment by rochacbruno** [comment]
https://github.com/HellerCommaA/flask-material-lite

**Comment by ellisonleao** [comment]
First version of the theme is done here https://github.com/quokkaproject/theme_material

**Comment by rochacbruno** [comment]
:+1: We can create an instance of demo website using this theme, I will think on how to do it!
