### ISSUE TITLE
Uploading images via TinyMCE or anather WYSIWYG editor

### ISSUE THREAD

**Issue by Arnack** [quokkaproject/quokka#286]
Is it possible?

**Comment by rochacbruno** [comment]
It is possible via plugin, but is not implemented yet, there is issues opened #127 and also we are going to replace TinyMCE with summernote which has native upload plugin and base64 image support #231 that changes will be implemented soon.

**Comment by rochacbruno** [comment]
base64 images is noe supported by summernote.
