### ISSUE TITLE
"Tried to save duplicate unique keys" error

### ISSUE THREAD

**Issue by superleemo** [quokkaproject/quokka#299]
I used "python manage.py populate" to generate initial data,then i run quokka,and error came out：

WARNING in fixtures [/home/superlimo/quokkacms/myquokka/quokka/ext/fixtures.py:26]:
## Could not create initial user and post

Tried to save duplicate unique keys (insertDocument :: caused by :: 11000 E11000 duplicate key error index: quokka_db.user.$email_1  dup key: { : "admin@quokkaproject.org" })

**Comment by rochacbruno** [comment]
:+1: I will take a look, maybe it is just a warning, but I will check.

**Comment by superleemo** [comment]
It's just a version issue,i used an old version,now issues have been fixed! And now quokka works fine!
great job,rochacbruno ! 
I love quokka soooooo much!
