### ISSUE TITLE
Settings not generic. 

### ISSUE THREAD

**Issue by kevinbowrin** [quokkaproject/quokka#3]
Settings are not generic on first install. (mongodb not localhost, secret key not auto-generated, Flask-Mail settings, etc).

How do we want to handle this? I don't mind the settings file like it is, makes for easier provisioning. However, I like the idea of writing the settings file in a wizard-like way, after bootstrap and with a one-time-use admin account.

**Comment by rochacbruno** [comment]
You are right! I cleaned up the need for email and changed mongo to localhost. a6e6f99710466f01218c820015d7e49534f99246

I will take a closer look to create a generic settings. help is very welcome on organizing this. thanks!
