### ISSUE TITLE
Implement REST API

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#30]
Use https://github.com/nicolaiarocci/eve  as default API layer, make it optional.

**Comment by rochacbruno** [comment]
https://github.com/elasticsales/flask-mongorest

**Comment by jniltinho** [comment]
flask-mongorest --> Cool + Simple + Fast
:+1: 
Great!

**Comment by rochacbruno** [comment]
https://github.com/gevious/flask_slither
