### ISSUE TITLE
pyshorteners does not get installed through requirements.txt

### ISSUE THREAD

**Issue by kgshv** [quokkaproject/quokka#303]
Hey there!
Awesome project!
Just installed it and wanted to play around when noticed that when installing things from requirements.txt with pip it gave me this output:

Downloading/unpacking pyshorteners==0.5.3 (from -r requirements/requirements.txt (line 19))
  Could not find any downloads that satisfy the requirement pyshorteners==0.5.3 (from -r requirements/requirements.txt (line 19))
  Some externally hosted files were ignored (use --allow-external pyshorteners to allow).
Cleaning up...
No distributions at all found for pyshorteners==0.5.3 (from -r requirements/requirements.txt (line 19))
Storing debug log for failure in /home/********/.pip/pip.log

So looks like no pyshorteners. I googled some and all links for pyshorteners v 0.5.3 seem to not be working (like the page for the module on pypi.python.org is indexed by Google but returns 404).

I then tried to just do "pip install pyshorteners", same result - "Could not find any downloads that satisfy the requirement pyshorteners". Did install after all after downloading their repo and running the install script.

I guess that's the pyshorteners issue more than yous, but thought you should know.

Good luck!

**Comment by ellisonleao** [comment]
Fixed!
