### ISSUE TITLE
can't delete role 

### ISSUE THREAD

**Issue by superleemo** [quokkaproject/quokka#305]
I created a new channel,and set an admin role,but after a while i don't want admin role ,so i delete the admin role in edit pannel and set role to none,but it doesn't work,and it still need an admin role,so i think this is a bug!

**Comment by oktools** [comment]
I can confirm that once a role is selected for a new or pre-existing channel, the "x" for removing it does not function fully. If the channel document has been saved with a role, it can no longer be saved without one -- it just keeps coming back. It can be switched to another role, or removed from a list of roles. 

These results were obtained using the most recent commit (8c5d96d).

**Comment by rochacbruno** [comment]
OK, thanks for reposting. I will take a look today.

**Comment by counsellors** [comment]
I meet the same problem, when the field looks like somethings = ListField(ReferenceField(SomeModel)), and the selected option couldn't be remove. Is it fixed in the new version ?

**Comment by counsellors** [comment]
It's be soveled. Because that I used an old version of quokka with flask-mongoengine-0.7.4,  and the problem has been found in [#148](https://github.com/MongoEngine/flask-mongoengine/issues/148).
