### ISSUE TITLE
How to upgrade quokka to the latest version?

### ISSUE THREAD

**Issue by netqyq** [quokkaproject/quokka#308]
jinja2.exceptions.TemplateNotFound: errors/server_error.html

**Comment by rochacbruno** [comment]
The template is there: https://github.com/quokkaproject/quokka/blob/development/quokka/themes/pure/templates/errors/server_error.html

Can you give more information? which theme are you using?

**Comment by netqyq** [comment]
[root@ctos errors]# pwd
/data/quokka/quokka/themes/pure/templates/errors
[root@ctos errors]# ls
access_forbidden.html  method_not_allowed.html  page_not_found.html  server_error.html

**Comment by netqyq** [comment]
thank you !

why I meet this error?
because I have deployed a previous version of quokka , calmops.com, I just want to update code to  
the latest version, so I encountered the error. 

I deployed the latest version from scratch this morning, it works well.
so the next step is how to update it to the latest version.

**Comment by realli** [comment]
@Chaniel , Do you check your configuration of  'DEFAULT_THEME'? 
Check the database also, the `config` table. I used to encounter such error, and found out one document set the `DEFAULT_THEME` to some value other than `pure`.

**Comment by netqyq** [comment]
![image](https://cloud.githubusercontent.com/assets/3492992/10510995/e685e400-7368-11e5-9687-4397370b70a7.png)

when DEFAULT_THEME = 'admin'   ,  it still not works

![image](https://cloud.githubusercontent.com/assets/3492992/10511004/fdb9d640-7368-11e5-945d-e29df6833e95.png)

**Comment by realli** [comment]
No, keep `DEFAULT_THEME` to `pure`. Can you connect to your mongodb database? If you can, you can check if there is one entry that sets the `DEFAULT_THEME` like this:

```
{
"content_format" : "html",
"available_at" : ISODate("2015-07-13T16:24:08.798Z"),
"created_at" : ISODate("2015-07-13T16:24:08.798Z"),
"updated_at" : ISODate("2015-07-13T16:24:08.798Z"),
"published" : false,
"values" : [
    {
        "name" : "DEFAULT_THEME",
        "rawvalue" : "default",
        "formatter" : "text"
    },
    {
        "name" : "ADMIN_THEME",
        "rawvalue" : "cosmo",
        "formatter" : "text"
    }
],
"group" : "settings",
"description" : "App settings override CAUTION!!!"
}
```

**Comment by netqyq** [comment]
I cant find  THEME like content in config collection.

{
    "_id": ObjectId("561943e700e5ab2a83f68cd2"),
    "values": [
        {
            "name": "EXAMPLE",
            "rawvalue": "this_overwrite_the_value_in_settings",
            "formatter": "text"
        }
    ],
    "content_format": "html",
    "available_at": ISODate("2015-10-11T00:59:19.577Z"),
    "created_at": ISODate("2015-10-11T00:59:19.577Z"),
    "updated_at": ISODate("2015-10-11T00:59:19.577Z"),
    "authors": [

```
],
"published": false,
"group": "settings",
"description": "App settings override CAUTION!!!"
```

}

**Comment by realli** [comment]
can you paste the full page of this error?

**Comment by zky001** [comment]
I also meet a seemed problem :8ball: TemplateNotFound: content/default_list.html.
I want to change some detail and test why.

**Comment by zky001** [comment]
@rochacbruno I can find my detail_list.html file at pure /.../default_list,but when i run server and open html file,the bug also at there.
@realli I also have no results by the way your discuss
