### ISSUE TITLE
The share links under each article are in a foreign language. Spanish I think.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#309]
Any idea how I can make them english?   This is a fresh install with my old database and old local_settings.py is there a one liner I should put in there? Thanks

**Comment by rochacbruno** [comment]
Good catch! 

It is in portuguese! https://github.com/quokkaproject/quokka/blob/development/quokka/themes/pure/templates/_helpers.html#L151

and https://github.com/quokkaproject/quokka/blob/development/quokka/themes/pure/templates/_helpers.html#L160

I will turn it into a configurable value.

**Comment by eurabilis** [comment]
look at that I found a minor bug and learned some Portuguese today
