### ISSUE TITLE
Control installed modules via database / remove the auto loader for blueprints

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#31]
I like the auto-load feature, you just drop a module folder and it is done! but it is error prone and I am already having trouble with naming problems.

Now the idea is to keep the folder /modules and the same blueprint structure, but it will not be autoloaded, to load a blueprint it will need to be activated in admin.

When you upload/extract a module in to /modules it will be automatically added to "available modules" but the default state will be **inactive**, so in admin you need to click in **activate** button and then it will perform validations, run the tests and check for naming issues.

It is urgent!

**Comment by yeradis** [comment]
one of the naming check should be also for custom blueprints routes, those added with module.add_url_rule like module.add_url_rule('/posts/', view_func=ListView.as_view('list')) to avoid conflits with existing routes

**Comment by rochacbruno** [comment]
Should support both methods
