### ISSUE TITLE
Where is the server root?

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#310]
I am trying to have a minecraft custom resourcepack in my quokka web server directory so when people connect to my server it will automatically download it. Basically im just trying to host a zip file. I notice robots.txt is in "static" so I put it in there and when I go to my sites url it works it does download it. The problem is it renames the zip file, "download" with no file extension and that's causing it not to work. http://sid.dontexist.dynu.com/static/purebdcraft128x.zip Whats a way I can get this to act as expected? Thanks

**Comment by rochacbruno** [comment]
For security reasons, /static will only serve files mapped here: https://github.com/quokkaproject/quokka/blob/development/quokka/settings.py#L55-L59

**Comment by rochacbruno** [comment]
So, put your file in static/filename and include in your local_settings

```
MAP_STATIC_ROOT = ('/robots.txt', '/sitemap.xml', '/favicon.ico', 'purebdcraft128x.zip')
```

In that way you can do site.com/purebdcraft128x.zip

But if you want a seamless solution, you can put the file in your theme static folder _themes/pure/static_. and access "http://sid.dontexist.dynu.com/_themes/pure/static/filename"

**Comment by eurabilis** [comment]
Excellent thank you.
