### ISSUE TITLE
How to change my avatar and profile settings seen on authors page?

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#312]
I cant seem to find any documentation on this, but I remember seeing something somewhere about gravatar so I set up an account there and I made a hash. Can I see an example line you would put in local_settings.py for my gravatar and where do I edit my profile settings that are seen on the authors page? Lastly, how do I change those share links from portugese to english?  Thanks.

**Comment by eurabilis** [comment]
Why is my avatar working all of a sudden and I didnt do anything to my knowledge. Are you guys messing with me :+1: Did just making a gravatar account automagically make quokka pull it in? thats impressive.

**Comment by rochacbruno** [comment]
the avatar is related to the email account you registered at gravatar.com service.

Go to admin and change the gravatar email and your profile info in accounts/users

**Comment by eurabilis** [comment]
Thats clever I like that as long as gravatar stays reliable.  I edited it all but it still says "none" "none" here http://sid.dontexist.dynu.com/author/michael_james_delvalle_gmail_com/ what did I  miss? Or does it need time to update. Thanks.

**Comment by rochacbruno** [comment]
No time needed. If you changed tagline and bio fields should appear there
