### ISSUE TITLE
TemplateNotFound error after upgrade to laest

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#314]
After update to latest quokka and related packages, I can't make it run as before, two issues are observed:
Problem 1:
"UndefinedError: 'get_url' is undefined". error when click Account->User
....
File "/slowfs/char_slow8/yuwang/tools/Python-2.7.3/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 24, in block "model_menu_bar"
<a href="{{ get_url('.create_view', url=return_url) }}" title="{{ _gettext('Create new record') }}">{{ _gettext('Create') }}</a>
UndefinedError: 'get_url' is undefined
-- Fixed after I modify bootstrap2/admin/model/list.html to use correct get_url. 

Problem 2:
Click Settings->Inspector, it reports "TemplateNotFound: content/portal_list.html". Not sure which env changed in Flask or Quokka.
...
Trying to load last template admin/inspector.html in cosmo
Trying to load last template admin/inspector.html in default
Trying to load last template admin/inspector.html in app templates

**Comment by rochacbruno** [comment]
You have to upgrade your requirements
"pip install -t requirements/requirements.txt -upgrade"

Also take a look in your database "config" collection or in your settings file.

ADMIN_THEME changed from "cosmo" to "admin"

**Comment by QiXuanWang** [comment]
I've tried all methods including clone a completlynew quokka and uninstall all packages in Python and reinstall them but still same error. 
I tried "pip install -r requirements/requirements.txt --upgrade" but it doesn't help.
ADMIN_THEME is "admin" since I'm using a new file.

I tried to visit localhost:my_port/ directly, and it reports in unix shell:
Rendering template:
theme [u'default'] - template [u'content/home/portal_list.html', u'content/portal_list.html'] - fallback True -context {'contens' : <flask_mongoengine.pagination.Paginaton object at 0x1c6a5390>, 'cannel':<Channel: home>}
trying to render content/home/portal_list.html in default 
.....
I'm not sure why it added "home" directory for me. Would it be the old database? 
I'll try to use a new database and try again.

**Comment by QiXuanWang** [comment]
OK. I confirmed that it's the database issue. Somehow old database could not be used. I'm not sure what's the root cause: flask or quokka. But if it's related quokka, please be kind to fix it. Or if you know it's related to other package, please let me know and I'll try to report an issue.

**Comment by rochacbruno** [comment]
I Guess the problem is because you have ADMIN_THEME setted in config.settings collection in database. Open your Mongo in Robomongo and change or delete that key from DB. I will think in a way to automate this in future upgrades

**Comment by QiXuanWang** [comment]
Right. Thanks. This problem should be OK now. I can get it work again.
