### ISSUE TITLE
Cannot delete a channel I made called World-news. This is the error I get.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#315]
I made a channel called World-news and changed my mind. I went to delete it and I get this error. 

`2015/10/30 11:32:42 [error] 1143#0: *227 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.2, server: sid.dontexist.dynu.com, request: "POST /admin/channel/delete/ HTTP/1.1", upstream: "uwsgi://unix:///home/quokka/sockets/quokka.socket:", host: "sid.dontexist.dynu.com", referrer: "http://sid.dontexist.dynu.com/admin/channel/"
root@sid:/var/log/nginx#`

Everything else works as expected. The database server is a seperate machine and all seems to be in working order there with permissions etc. I also tried to delete it, got the error and went and tailed the mongodb log and nothing was out of the ordinary. How can I delete this category? Also as a sidenote: the google-plus share link is still in portugese how can I change that to english? #309 Thanks!

**Comment by eurabilis** [comment]
`mongoengine.errors.OperationError: Could not delete document Content.channel refers to it
[pid: 1191|app: 0|req: 17/53] 192.168.1.2 () {54 vars in 1491 bytes} [Fri Oct 30 19:18:22 2015] POST /admin/channel/delete/ => generated 0 bytes in 78 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)`

For anyone that cares that was why. I seen this error in /var/log/uwsgi/quokka.log and I realized there was still a unpublished post using articles/world-news. Both have been deleted thanks anyway. 

Theres still the google-plus being in portugese issue though.

**Comment by rochacbruno** [comment]
I am thinking on a solution, create an action (which will must be confirmed by password) on channel list.

[ x ] channel name -> with selected -> delete all contents | move contents to another channel | publish/unpublish contents.

I will so some tests on this.

Than you for reporting the issues! you are helping a lot the evolution of the project!

**Comment by eurabilis** [comment]
Old thread closing.
