### ISSUE TITLE
default settings

### ISSUE THREAD

**Issue by avelino** [quokkaproject/quokka#323]
```
MONGODB_DB = "quokka_db"
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_USERNAME = None
MONGODB_PASSWORD = None
```

to: 

```
MONGODB_DB = os.getenv("QUOKKA_MONGODB_DB", "quokka_db")
MONGODB_HOST = os.getenv("QUOKKA_MONGODB_HOST", 'localhost')
MONGODB_PORT = os.getenv("QUOKKA_MONGODB_PORT", 27017)
MONGODB_USERNAME = os.getenv("QUOKKA_MONGODB_USERNAME", None)
MONGODB_PASSWORD = os.getenv("QUOKKA_MONGODB_PASSWORD", None)
```

for all default setting. It helps to use cloud system

**Comment by rochacbruno** [comment]
It is already done here: https://github.com/quokkaproject/quokka/blob/development/quokka/core/config.py#L107

The config must always be read using app.config, current_app.conf or quokka.utils.get_setting, that way any env var named QUOKKA_\* will be there replacing config values.
