### ISSUE TITLE
AttributeError: is_homepage

### ISSUE THREAD

**Issue by avelino** [quokkaproject/quokka#327]
Up new site now and return error, branch developer

https://i.imgur.com/4yJlD4I.png

**Comment by avelino** [comment]
checkou to aec69f34d38842adf5e5c150c37c3816b91b57e7

I've deleted the database again and climbed the quokka and it worked.

**Comment by rochacbruno** [comment]
I've test again, following strictly the https://github.com/quokkaproject/docker-gunicorn-supervisor/blob/master/README.md instructions.

It worked well if you run **manage.py populate** as the last step.

There are 2 problems.
1. When **docker-compose up** starts it does not ensure the order of loading, in other words, Gunicorn starts serving quokka app before MongoDB is ready. For that I included a note to run "docker-compose run mongo" once before.
2. The same problem is happening when **docker-compose up** starts again. Quokka has a script in ext/fixtures that tries to load base needed data, default configs, base channels, homepage etc.. if mongo is not responding it fails silently. 

Solution: We need to refactor ext/fixtures to use @retry or another way to ensure base fixtures are loaded & we need a way to start serving quokka only after MongoDB is available.

**Comment by rochacbruno** [comment]
BTW: If run any command in shell

```
docker-compose run --rm quokka python manage.py shell
```

or

```
docker-compose run --rm quokka python manage.py populate
```

It magically works

Maybe we need a mandatory command?

```
docker-compose run --rm quokka python manage.py install
```

??
