### ISSUE TITLE
upload a image error

### ISSUE THREAD

**Issue by javalurker** [quokkaproject/quokka#33]
i uploaded a image (test.jpg).it produced tow images.
test.jpg( it's a fail image)
test_thumb.jpg( it's ok )

windows7 64bit ,python 2.7.3

**Comment by rochacbruno** [comment]
I opened an issue in mrjoes/flask-admin#300 as it seems to be an error in Flask admin widget.

Thanks again for reporting.

**Comment by rochacbruno** [comment]
Tested with jpeg, png and jpg on Linux with Pillow it worked well. I am going to close this issue, if needed please open it again.
