### ISSUE TITLE
DynamoDB support?

### ISSUE THREAD

**Issue by Miserlou** [quokkaproject/quokka#335]
If Quokka supported DynamoDB, we could run it on AWS super easily! Zappa + Quokka would be the easiest possible way to get a CMS up and running. They're both NoSQL databases.. any chance you'd consider supporting DynamoDB as a backend?

**Comment by rochacbruno** [comment]
Quokka uses MongoEngine, If somebody creates a "MongoEngine Like Layer" to communicate with Dynamo, Postgresql etc.. it will be possible to make Quokka to work with that backends.

I am for example working in ESEngine (a Mongoengine like layer for ElasticSearch and maybe Quokka will run entirelly on E.S in future)
