### ISSUE TITLE
I have to bother you with something stupid.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#336]
Hello all, I am trying to change my domain name from sid.dontexist.dynu.com to minecraftmafia.co... so i edited all the links etc, and I went in admin > site > preferences and changed all instances of the old domains but they are greyed out. They let me change them.. But they are greyed out. And when I go here http://minecraftmafia.co the TITLE.. aka the host line on the top of the browser gui (or the tab in chrome.) still has the old domain and I cant figure out where its coming from. I grepped the entire themes filetree and I think its embedded in the database or something. How do I change that please? Thanks and keepp up the good work gentlemen

**Comment by rochacbruno** [comment]
Those settings comes from config - site - Site name which theme are you
using?

On Tue, Mar 8, 2016 at 11:02 PM, eurabilis notifications@github.com wrote:

> I am trying to change my domain name from sid.dontexist.dynu.com to
> minecraftmafia.co... so i edited all the links etc, and I went in admin >
> site > preferences and changed all instances of the old domains but they
> are greyed out. They let me change them.. But they are greyed out. And when
> I go here http://minecraftmafia.co the TITLE.. aka the host line on the
> top of the browser gui still has the old domain and I cant figure out where
> its coming from. I grepped the entire themes filetree and I think its
> embedded in the database or something. How do I change that please? Thanks
> and keepp up the good work gentlemen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rochacbruno/quokka/issues/336.

## 

_Bruno Rocha - @rochacbruno http://twitter.com/rochacbruno_
http://brunorocha.org
http://github.com/rochacbruno
http://linkedin.com/in/rochacbruno
http://plus.google.com/+BrunoRocha1  http://plus.google.com/+BrunoRocha1

**Comment by eurabilis** [comment]
I'm using pure thanks

**Comment by eurabilis** [comment]
Yeah, config > site > site name is greyed out. it lets me change it but it doesnt keep.

**Comment by rochacbruno** [comment]
Humm I am trying to find the issue, maybe it is being cached.. I will try to do it by tomorrow

**Comment by eurabilis** [comment]
it's no big deal take your time and thanks

**Comment by gustavofc** [comment]
I didn't succeed at reproduce this issue. Maybe it's already resolved.

**Comment by eurabilis** [comment]
Thanks guys
