### ISSUE TITLE
Integrating with a new Url Shortener(WP-A.CO)

### ISSUE THREAD

**Issue by vmesel** [quokkaproject/quokka#341]
So I've seen that the Quokka CMS is already integrated with a URL Shortener(Bit.ly), and I've read the source code and it involves the API, why we don't use an Open Source URL Shortener like WP-A.CO that comes with an easy to use API(the shortener is developed by me, so any changes needed we can make).

**Comment by rochacbruno** [comment]
@vmesel nice! opensource is always welcome, quokka is using urlshortener by @ellisonleao maybe this suport has to be added on that module first.

**Comment by ellisonleao** [comment]
I can take this one!

**Comment by vmesel** [comment]
@ellisonleao if you join the Quokka Slack would be awesome, so we can talk about it!

**Comment by ellisonleao** [comment]
Issue opened https://github.com/ellisonleao/pyshorteners/issues/40
