### ISSUE TITLE
Will Quokka support Python 3 in the future?

### ISSUE THREAD

**Issue by prob1995** [quokkaproject/quokka#346]
It would be more happy if quokka support python 3 :)

**Comment by alexandre** [comment]
hello @prob1995 ,

I've started to work in such support. But, let me ask: have you tried to use quokka with python3?

Please, do it and report bugs, if possible. IMO, it's the best way to we improve the python3 support. =]

I'll try to work on this issue at this week.

[ ]'s

**Comment by prob1995** [comment]
Hihi, thanks for your reply.

I tried to use quokka in pyhton 3.5 with MacOS.
When I start to run the project by
`python manage.py runserver`
it shows lots of "current_app is inaccessible: working outside of application context"

<img width="664" alt="2016-04-19 6 13 30" src="https://cloud.githubusercontent.com/assets/9880748/14635863/dbabcac4-065a-11e6-87f8-1a74d01274d6.png">

The local site started running anyway. Then, the error came up when I try to post an article.

<img width="772" alt="2016-04-19 6 33 31" src="https://cloud.githubusercontent.com/assets/9880748/14636344/7d2d15a4-065d-11e6-9e52-c04a39de6504.png">

It shows "NameError: name 'unicode' is not defined" 

<img width="1229" alt="2016-04-19 6 12 35" src="https://cloud.githubusercontent.com/assets/9880748/14636358/90e0b588-065d-11e6-8595-88ac0793b93d.png">

I tried to resolve this issue on internet. It seems that is because this package doesn't support python 3.
http://stackoverflow.com/questions/24397842/unicode-is-not-defined-error-flask-flatpages-and-python-3

I guess this is because Quokka only support Python 2.7. To make it on Python 3 seems not easy.
Now I am using python 2.7 with Quokka, It seems fine. However, I am more familiar with Python 3. If Quokka can be used in Python 3, it would be great! Please let me know!

**Comment by alexandre** [comment]
@prob1995 ,

Many thanks by your report. I know how to fix it (all strings are unicode in python3, there is no "basestring vs unicode". And If you need bytes, you need to specify it.)

> I guess this is because Quokka only support Python 2.7. To make it on Python 3 seems not easy.

Actually, we already have an initial support, this kind of issue helps a lot to improve it more and more.

>  If Quokka can be used in Python 3, it would be great! Please let me know!

Sure, I agree 100%.

**Comment by alexandre** [comment]
SitRep:

The flask-htmlbuilder must to be upgraded on the pypi. @rochacbruno may you do it?

I tested the same flow that the @prob1995 , but using the version available on github and worked fine. I also <del>did git push</del> opened a pull request to the branch python3 change updating the requirements.txt to use the github version.

**Comment by rochacbruno** [comment]
@alexandre ok, going to merge, and also update the PyPI pack, sorry the delay..

**Comment by alexandre** [comment]
@rochacbruno no problems. Just update this issue when you do it.[please]

@prob1995 after it, if possible, could you back to try quokka with python3? =]

Many thanks, guys.

**Comment by alexandre** [comment]
I'll try to work a bit more on the python3 issue at this weekend too.

**Comment by prob1995** [comment]
@alexandre  I've try on python3 to post an article. It works fine now. Thank you!

However, It still shows lots of 
"current_app is inaccessible: working outside of application context" 
when I try to create superuser and run server. I can still create super user and run the server after these warning. I guess the issue is in quokka.core.models. See below.

<img width="780" alt="2016-04-28 11 31 56" src="https://cloud.githubusercontent.com/assets/9880748/14874724/a3c4ff2c-0d35-11e6-867e-1889c44cdb12.png">

<img width="693" alt="2016-04-28 11 33 00" src="https://cloud.githubusercontent.com/assets/9880748/14874727/aa90310a-0d35-11e6-8f6d-59c8d15bf130.png">

**Comment by alexandre** [comment]
@prob1995 ,

Ok, I saw that warning too and I think I can solve it. I also will try a kind of flow (create user -> post -> comment -> update post) looking for similar problems.

Thanks for your reports/comments. :]

**Comment by rochacbruno** [comment]
Thanks @alexandre - I am not able to work here this week, but I'll reserve some time next week to help on this.

**Comment by alexandre** [comment]
Hi guys,

The problem is [a little bit] bigger than I thought. There is a new rule about imports in Python3 that is responsible by this errors (AFAIK).
I'm trying to fix it (reading about how others projects fixed it) and I'll update this issue after do it.

**Comment by kinganu** [comment]
Guys, was having the same question.  I run a stack with python3.5, flask, ubuntu 16, apache2, and need a good cms.  If you having trouble importing custom modules try a relative import with a  . in front:

from .dbconnect import connection

Recently this fixed an import issue I had that broke my app.  Anyways Id like to see a tutorial setting up Quokka CMS for blog, forum, or user based website.  Does quokka have a module for creating a forum or do I need to find another extension for that?  Thanks.  Just need a CMS figured out (hopefully this wont be too convoluted to set up) so I can launch some websites.

**Comment by alexandre** [comment]
@kinganu ,

I'm still working on this issue (no progress for now), but yes, that's the idea. :] (relative imports)

About your question:

> Does quokka have a module for creating a forum or do I need to find another extension for that? 

What about open an issue to talk about it? (Just to not lose the goal here :])

**Comment by bmjjr** [comment]
Hi, just want to check if it's python3 compatible now? Thanks.
