### ISSUE TITLE
failed when uploading images

### ISSUE THREAD

**Issue by chansource** [quokkaproject/quokka#347]
i tried to upload an image. But something went wrong. Below are the error messages.
how can i fix it? Thank you in advance!
![image](https://cloud.githubusercontent.com/assets/9208028/14671448/6b6d8908-0724-11e6-82ac-4b0ac15c5be3.png)
![u7p16y vcymwc7 oy4mbx](https://cloud.githubusercontent.com/assets/9208028/14671535/e1c72a50-0724-11e6-8307-82cb1f4e48e7.png)

**Comment by Roukoswarf** [comment]
I can verify this is a problem on python 3.5 with any image upload using the image media list.
The self.path object in this context is empty, the object seems otherwise populated fine.

This crash happens any time you try to view the image media list after uploading an image, and kills the entire menu permanently.

**Comment by Roukoswarf** [comment]
It looks like the upload isn't actually putting the file anywhere yet, after quickly glancing over the code.

A way to stop the crashing if it's bothering anyone would be to dump the image records from the mongodb and use a different method for your media until fixed.
`db.content.remove({"_cls":"Content.Media.Image"})`

**Comment by superleemo** [comment]
please fix this bug as soon as possible!!

**Comment by rochacbruno** [comment]
I thought it was fixed in development branch, let me check @fxxku have you tried this recently?

**Comment by eurabilis** [comment]
Is this the same bug as mine? #404

**Comment by heyton** [comment]
Same error:

> TypeError: expected str, bytes or os.PathLike object, not _LazyString
