### ISSUE TITLE
Disqus is the only working comment module?

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#349]
I saw in _helpers.html:
        {% if Config.get('comments', 'system') == 'internal' %}
            <div id="comment-area" data-system="internal" data-path="{{url_for('quokka.modules.comments.comment', path=content.long_slug)}}"></div>
        {% elif Config.get('comments', 'system') == 'custom'%}
            {{Config.get('comments', 'custom_script', '')|safe()}}
        {% elif Config.get('comments', 'system') == 'disqus'%}
And in Admin->Settings->Config, "internal" and "disqus" are two options.
But somehow I don't see why "internal" could work since there is no "quokka.modules.comments.comment"? 
So is "disqus" the only comment system built in? What if I want to use some other version?

**Comment by rochacbruno** [comment]
The internal comment module has been dropped and this template needs fix.

**Comment by QiXuanWang** [comment]
Thanks for the update. So what's the recommended comment system besides Disqus? 
Actually, can I just use a similar approach as disqus.html, to include another 3rd party comment system?
Would try it myself later but in case you have the expert suggetion...

**Comment by rochacbruno** [comment]
intensedebate works very well and is easy to implement
