### ISSUE TITLE
Minor Bug, is_homepage selector return exception

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#351]
When there is already homepage, if you set a new channel/post as homepage, it returns exception.
Ideally it should stop you from doing this at the check box, even a proper error would be more appropriate instead of exception.
It won't impact anything so far.

**Comment by rochacbruno** [comment]
Well it maybe easy to disable the checkbox I'll see

**Comment by QiXuanWang** [comment]
Actually I also found some other exception reported when I tried to save something existed. This is not the normal "save" action for a post. I can't recall the situation though. Maybe a if existed check should be added. Will see if I can reproduce it later on.
