### ISSUE TITLE
Wrapper to WordPress API

### ISSUE THREAD

**Issue by gutomaia** [quokkaproject/quokka#354]
End point plugins that are compatible to WordPress API.

If someday someone decide to remove WordPress t
From their stack. Quokka will be already compatible.

**Comment by andrelramos** [comment]
Sorry for my silliness, but, how is possible itegrate a python project with a php project?

**Comment by rochacbruno** [comment]
@andrelramos the idea is to have a command in Quokka to read data from wordpress API and populate into Quokka database.

**Comment by andrelramos** [comment]
@rochacbruno Cool. Do you need help to do this? I can help it
