### ISSUE TITLE
[Deploy] Some experience sharing 

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#356]
1. Ubuntu16 or Debian8 uses systemd while not upstart. so old script for auto start service will not work. Users will need to follow other instructions online to deploy.
2. gunicorn works for me on ubuntu16.04. uwsgi failed once but I may need to test again,
3. Still quite some random crashes...
4. The starting Warnings are annoying. Not sure it's just me or in general.
5. Somehow Flask-Cache doesn't work for me...

**Comment by rochacbruno** [comment]
Thanks for sharing, so we need a ubuntu 16 install script @jniltinho
