### ISSUE TITLE
Markdown in body

### ISSUE THREAD

**Issue by jonasteuwen** [quokkaproject/quokka#36]
I would like to propose to allow Markdown as input for the body text in the admin interface. For instance lepture: http://lab.lepture.com/editor/ is a nice editor for this.

Markdown would separate content and design more, while still allowing the use of HTML. What would be the most convenient way to detect which editor to use? I gave it a class markdown-editor or html-editor.

Implementation is really simple with https://flask-misaka.readthedocs.org/en/latest/ and we can always cache the html output, so no performance loss.

Another advantage is that Markdown is easy to read even without parser. This stored in the database can have strong advantages for the eventual API.

**Comment by avelino** [comment]
:+1:

**Comment by rochacbruno** [comment]
:+1: 
Great!

We need to implement that in a way the **editor** can choose the input format. SO in the **Post** we need to add a field **format** and defaults it to **DEFAULT_FORMAT** settings.

A **dropdown** in admin Post page will switch format and the editor, so we can support HTML, Creole, Markdown, .rst and also custom formats.

**Comment by jonasteuwen** [comment]
But the channels can have some content as well, right? Are such properties not better part of the object itself (the body) rather than the post? Perhaps as an EmbeddedDocument, as I assume that 'flat' is faster in MongoDB (but I am by no means an expert).

**Comment by rochacbruno** [comment]
I was thinking in adding **content_format** in the **Post** class https://github.com/pythonhub/quokka/blob/master/quokka/modules/posts/models.py#L8

``` python

DEFAULT_FORMAT = "html"
FORMAT_CHOICES = ("html", "rst", "creole", "markdown", "latex")

class Post(Content):
    body = db.StringField(required=True)
    format = db.StringField(choices=FORMAT_CHOICES, default=DEFAULT_FORMAT)
```

So it would be used directly in template to render the content within a template filter

`{{ post.body | format_content(post.format) }}`

or maybe we can define **content_parser** as a method of **Post** class

`{{ post.parsed_body }}`

Also for the **textarea** in Flask-Admin we will need to write a customized widget, which will be **lazy** (have to check if tinymce supports lazy binding). So inside the admin just switch from available formats and the JS editor changes from tinymce, lepture, creoleeditor etc...

What are the details of implementation you was thinking @jonasteuwen ? having **body** as an EmbeddedDocument? and inside it `{'format': 'html', 'content': '<p>blabla</p>'}`, will it be practical to implement the editor in admin?

**Comment by rochacbruno** [comment]
BTW: Channels are not meant to have content **body** only a description to be used is a list of channels, **channels** are just content aggregates, just like categories or folders. We can add Posts or another contents inside it, so I think we can have it only for Post. What do you think?

For new modules, if the Model needs a "body" and a "format" only need to inherit **Post** directly, other contents can inherit **Content**.

**Comment by jonasteuwen** [comment]
A lot of information!

The idea is good, I have yet to get a bit accustomed to channels/posts as the latter have .html extension, which is not my preference (but, different topic!)

It sounds good, but I would prefer if we do not need to define the parser in the template, the template should just get html. If the parser is set in the document, we can already parse out html right?

```
class Body(db.EmbeddedDocument):
    body = ...
    parser = ...

    def __unicode__(self):
        return parsed_body()
```

Or something similar, as the body should in my opinion consist of: the content, a set of rules on how to read it. Of course, it will look the same in the database so I might be missing something or be too idealistic. The main point is that once you put it in a template, it should be already parsed into html for a browser, or json for the api, etc.

All this aside, we should make sure, we do not do work that would have been done differently if we were to also implement something like createjs.org :-).

**Comment by rochacbruno** [comment]
Implemented!
