### ISSUE TITLE
[Possible python3 bug] Always an extra "None" author added to every post

### ISSUE THREAD

**Issue by Roukoswarf** [quokkaproject/quokka#365]
When creating a new post on python 3.5.2 with a single author, there always appears another author of None appended to the list when pulling content.get_authors() from templates, this causes the multiple authors code in the pure theme to subsequently crash when it can't pull the display name of None.

Line 45, quokka/themes/pure/templates/_menu.html

```
{%for author in content.get_authors()|sort(attribute="display_name")%}

jinja2.exceptions.UndefinedError: 'None' has no attribute 'display_name'
```

When debugging at this breakpoint:

```
>>> content.get_authors()
set([<User: John Doe <user1>>, None])
```

Another interesting behavior is that selecting no author will not cause a "None" entry, and that trying to remove authors from the list and hitting save does nothing, while adding new authors does work.

**Comment by rochacbruno** [comment]
@Roukoswarf thanks for reporting, I think we should force get_authors() to return an empty list and clean Nones.

**Comment by Roukoswarf** [comment]
That would be good as it would allow authors to appear in order of mention in the article config, instead of being reshuffled alphabetically without user choice every time.

Though, finding where the extra none comes from would be needed, as there is some issues with removing authors not working that are likely a symptom of the same problem.

**Comment by rochacbruno** [comment]
@Roukoswarf the bug of None, and the order problem was fixed by @ramiroluz :)
