### ISSUE TITLE
problem when adding media/image

### ISSUE THREAD

**Issue by kuso** [quokkaproject/quokka#371]
Hello guys,

  I run into this problem when I try to add media/image in the admin page.  I am using a fresh installation of quokka with all the requirements installed, superuser created.  The first thing I do is that I go to the admin page, click on the image button, add an image and the following problem comes up.  I think the media/image is created and I can see it in mongodb, the problem seems to be related with flask_admin.  Can anybody help me with this?

![2016-07-20 9 22 27](https://cloud.githubusercontent.com/assets/147306/16972301/eb238ea2-4e5c-11e6-9fed-9a823f51fa08.png)

**Comment by rochacbruno** [comment]
column formatter has changed in flask admin, I'll take a look

**Comment by rochacbruno** [comment]
Looks like this problem has been solved 23 days ago in 'development' branch https://github.com/quokkaproject/quokka/commit/1c277a184925d8780a70e764bcb6cd047e86b3f2

**Comment by kuso** [comment]
thanks, it works now in the development branch
