### ISSUE TITLE
Flask-BabelEx==0.8.1

### ISSUE THREAD

**Issue by tonychenl** [quokkaproject/quokka#38]
No distributions matching the version for pytz (from Flask-BabelEx==0.8.1->-r requirements.txt (line
 20))

**Comment by mauricioabreu** [comment]
Well, here is a good answer to show why it is not working:
http://stackoverflow.com/a/18319230/2159486

You need to use the --pre flag to install a pre-release version.

More info here:

https://github.com/pypa/pip/issues/974

**Comment by tonychenl** [comment]
tks

**Comment by rochacbruno** [comment]
I will fix that in requirements. I guess I can just delete the versions. and for some packages install from github.

**Comment by tonychenl** [comment]
add --pre flag  I'm install success

**Comment by rochacbruno** [comment]
@tonychenl 

I tested in Linux and worked without the --pre

I want to include a note in README about this --pre issue, can you elaborate on why you have the error and how did you get this working?

Your O.S, Python version, and the steps you made to have it working? 

Thanks

**Comment by tonychenl** [comment]
OS:windows8
python:2.7.3
install quokka with 'pip install -r requirements.txt' got error ,
I'm trying 'pip install --pre  -r  requirements.txt' this time success

------------------ Original ------------------

**Comment by rochacbruno** [comment]
fixed
