### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by ChiliConSql** [quokkaproject/quokka#389]
Thank you for building a CMS based on Flask. I am very excited at the opportunity of using it, but I have one problem and one suggestion:
Instead of tying it MongoDB, why not hook it to a JSON adapter that can be used with Mongo or an API instead. I think that would make this project more flexible and appealing to a wider audience and possibly push it to top 5 list.

**Comment by rochacbruno** [comment]
tinydb is on te todo list, any help is welcome!

**Comment by rochacbruno** [comment]
http://tinydb.readthedocs.io/en/latest/

**Comment by ChiliConSql** [comment]
I'm not talking about another local json store. I'm talking about something like Firebase or any JSON API service.
