### ISSUE TITLE
a little bug of quokka/etc/scripts/setup-quokka-uwsgi-nginx-opensuse.sh 

### ISSUE THREAD

**Issue by battlecat** [quokkaproject/quokka#394]
a little bug was spawn when I deploy quokka with scripts on aws of amzlinux,the homepage can't display the png files of local.it seems that nginx can't display local static files.
So,I check again the nginx.conf and find the wrong of reg rule in setup-quokka-uwsgi-nginx-opensuse.sh.In line 82:
          location ~ ^/(static|mediafiles)/ {
should be : 
          location ^~ /(static|mediafiles)/ {
the bug is gone after I change the scripts files.

**Comment by rochacbruno** [comment]
@battlecat thanks, I'll update the script  (or send a Pull Request if you want)

Thanks
