### ISSUE TITLE
can't run manage accounts_createsuperuser

### ISSUE THREAD

**Issue by javago** [quokkaproject/quokka#395]
The First 
(venv) D:\Person\study\quokka>python manage.py accounts_createsuperuser
python: can't open file 'manage.py': [Errno 2] No such file or directory.
There isn't manage.py file.

Second:
I try to pip install manage .finish manage module setup.
(venv) D:\Person\study\quokka\quokka>manage populate
Usage: manage [OPTIONS] COMMAND [ARGS]...

Error: No such command "populate".
![image](https://cloud.githubusercontent.com/assets/2667720/18876874/dfce0a1e-84fd-11e6-93ae-1e9d26b1fc36.png)

**Comment by rochacbruno** [comment]
Never tested this on windows.

But looks like you are in the wrong root directory, you should use study\quokka root, there will be a `manage.yml` there you dont need to init by yourself.

**Comment by javago** [comment]
![image](https://cloud.githubusercontent.com/assets/2667720/18879278/3d6afa26-8506-11e6-8968-2f7df59e6f83.png)
in root directory

**Comment by rochacbruno** [comment]
something is wrong with windows support, never tested, so I'll need some help to make it work on that "operating system".

**Comment by GERMANOCARELLA** [comment]
Ok, I've the same problem. I have manage.ml, but, how can I run it? I need some package to run this yml file?

**Comment by pingpongcult** [comment]
![quokka](https://cloud.githubusercontent.com/assets/18239811/22699231/e13cb89e-ed91-11e6-9583-68b5683b3d20.png)
![quokka](https://cloud.githubusercontent.com/assets/18239811/22699297/0996a39a-ed92-11e6-90ad-4bcc3e4f5eb6.png)
I also have same thing on ubuntu16.04

**Comment by rochacbruno** [comment]
Are you using Python3 ? All requirements installed?

**Comment by pingpongcult** [comment]
@rochacbruno quokka is running when git clone again

**Comment by sergiobrr** [comment]
Same issue here on ubuntu 16.10

What i do:
`$ git clone https://github.com/quokkaproject/quokka --branch master --single-branch`
`$ mkvirtualenv quokka`
`(quokka)$ cd quokka`


Folder structure:

![image](https://cloud.githubusercontent.com/assets/6337160/22850157/4e44d460-f005-11e6-80e2-4d67bd028968.png)

`(quokka)$ pip install -r requirements/requirements.txt`

Then i rename example.local_settings.py to local_settings.py and change the db name:
MONGODB_DB = "quokka"
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_USERNAME = None
MONGODB_PASSWORD = None

then:
`(quokka)$ manage accounts_createsuperuser`
Traceback (most recent call last):
  File "/home/sergio/virt/quokka/bin/manage", line 11, in <module>
    sys.exit(main())
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/manage/cli.py", line 214, in main
    manager = init_cli(cli)
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/manage/cli.py", line 204, in init_cli
    load_commands(cli, MANAGE_DICT)
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/manage/commands_collector.py", line 90, in load_commands
    root_module = import_string(command_dict['module'])
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 49, in import_string
    module = import_string(module_name)
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 49, in import_string
    module = import_string(module_name)
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/import_string/base.py", line 36, in import_string
    __import__(import_name)
  File "./quokka/__init__.py", line 9, in <module>
    from quokka.core.admin import create_admin  # noqa
  File "./quokka/core/admin/__init__.py", line 7, in <module>
    from quokka.core.models.subcontent import SubContentPurpose
  File "./quokka/core/models/subcontent.py", line 6, in <module>
    from quokka.core.db import db
  File "./quokka/core/db.py", line 4, in <module>
    from flask_mongoengine import (
  File "/home/sergio/virt/quokka/local/lib/python2.7/site-packages/flask_mongoengine/__init__.py", line 16, in <module>
    from mongoengine.base import ValidationError
import_string.base.ImportStringError: import_string() failed for 'quokka.core.commands'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportStringError: import_string() failed for 'quokka.core'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportStringError: import_string() failed for 'quokka'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportError: cannot import name ValidationError

Same thing if i use different virtualenv name (testcms for example), a different folder structure and rename quokka root as src:

![image](https://cloud.githubusercontent.com/assets/6337160/22850137/254e7b2e-f005-11e6-9d05-0da022985fc8.png)

**Comment by sergiobrr** [comment]
I updated flask mongoengine to version 0.8.2 and it seems solved.
now manage execute commands and runserver works

**Comment by johnsonchak** [comment]
@sergiobrr i also have a problem that manage fails to execute.it said This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
current_app is inaccessible: Working outside of application context.

**Comment by heyton** [comment]
@johnsonchak same
