### ISSUE TITLE
Docs - quokka not in quokka-env

### ISSUE THREAD

**Issue by kevinbowrin** [quokkaproject/quokka#4]
Should the docs say: 

```
~/$ virtualenv quokka-env
~/$ ... creating virtualenv in quokka-env........
~/$ cd quokka-env
~/$ source bin/activate
~/$ git clone https://github.com/rochacbruno/quokka
~/$ ...cloning in to quokka
```

Or is this just my personal preference? (I like the app to be in the virtualenv which you source).

**Comment by rochacbruno** [comment]
I prefer to keep app source in a different place because sometimes I use the same env to run more than one branch or copy of the same project. 

But I guess you are right, for the most part of the people projects stays inside the env folder. changing it.

**Comment by kevinbowrin** [comment]
One great thing about virtualenv - no wrong way to do it. 

Thanks for the quick turn around on these :D
