### ISSUE TITLE
Cannot click "images" button on bottom of admin panel

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#404]
You know, the button that says "images" next to "users" and "upload" ? in admin panel? It tries to load "http://www.minecraftmafia.co/admin/image/" and then the server crashes. I get "502 Bad gateway" and this is in the log:

`root » [app]: tail quokka.log
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'quokka.core.media'. Did you forget to specify values ['filename']?
[pid: 3825|app: 0|req: 1/1] 73.159.133.252 () {48 vars in 1432 bytes} [Wed Oct 19 23:08:58 2016] GET /admin/image/ => generated 0 bytes in 3378 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
root » [app]:`

`my settings.py has:
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'mediafiles')
and the directory exists because I created it. it has directories in it, dated 2016.

  {
        "name": "Media files",
        "category": "Files",
        "path": MEDIA_ROOT,
        "url": "/mediafiles/",  # Create nginx rule
        "endpoint": "media_files",  <<<<<<IS THIS CORRECT? I TRIED "mediafiles" same result. 
        "roles_accepted": ("admin", "editor"),
        "editable_extensions": DEFAULT_EDITABLE_EXTENSIONS
    }`

I also cant click up top, media,image. anything that goes to http://www.minecraftmafia.co/admin/image/ crashes
THANK YOU!!

**Comment by rochacbruno** [comment]
Maybe it was the Pillow upgrade, I am going to test it.

**Comment by eurabilis** [comment]
I downgraded pillow to 3.4.0 and ran  pip install --upgrade --force-reinstall -r requirements/requirements.txt and had the same problem. HTH

**Comment by eurabilis** [comment]
trying Pillow==3.3.1 now.

**Comment by eurabilis** [comment]
File "/home/quokkaenv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'quokka.core.media'. Did you forget to specify values ['filename']?

Same crash witht his error, and also these two in quokka.log when first starting. 

INFO in blueprints [./quokka/ext/blueprints.py:51]:
authors module does not define admin or error: No module named admin

No handlers could be found for logger "root"

**Comment by eurabilis** [comment]
This fixed itself as I updated debian to SID unstable/testing and also updated quokka to ddevelopment. Not sure exactlyt what fixed it. see #405
