### ISSUE TITLE
I installed the development branch because I read my bug was fixed but its not.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#405]
1: "No handlers could be found for logger "root""

2: "INFO in blueprints [./quokka/ext/blueprints.py:51]:
authors module does not define admin or error: No module named admin"

It still crashes when I attempt to go to siteurl/admin/image/ and it introduced the above errors as well. Do I need to upgrade my database for the new development version? can you tell me how? thanks.

**Comment by rochacbruno** [comment]
@eurabilis maybe it is a different bug, are you on which O.S?

**Comment by eurabilis** [comment]
@rochabruno quokka is on debian 8.6 "jessie" and my database server dual boots so it is either in arch linux or windows 10, as both run an in sync mongoDB database. Recently, I decided to upgrade quokka to the latest code so I deleted quokkaenv completely and installed with the latest Master branch, which introduced my siteurl/admin/image/ crashing problem. So then I wiped and installed the development branch, still giving me the original problem as well as the ones above. Hope that helps.

**Comment by eurabilis** [comment]
Updating to debian SID UNstable (TESTING) and reinstalling quokka to the development branch fixed these problems. I perused the log files and still see these here:

Mon Jan  9 17:24:53 2017 - *** Operational MODE: preforking ***
No handlers could be found for logger "root"
./quokka/ext/generic.py:10: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  CsrfProtect(app)
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:43]:
registering blueprint: quokka.modules.media
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:43]:
registering blueprint: quokka.modules.authors
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:51]:
authors module does not define admin or error: No module named admin
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:43]:
registering blueprint: quokka.modules.accounts
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:43]:
registering blueprint: quokka.modules.posts
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in blueprints [./quokka/ext/blueprints.py:43]:
registering blueprint: quokka.modules.comments



BUT! I can click the images button now and i do not get a crash. Ill close this now as these messages, to me at least are superficial and do no damage that i can see. Thanks.
