### ISSUE TITLE
Is the MongoDB structure different between versions and between master and development?

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#406]
Is the MongoDB structure different between versions and between master and development?
I am having problems because I am now using an up to date version of quokka but my DB is older because I dont want to lose my content. Specifically, I think the way you are putting users in the DB is different now. I would like to update those types of changes, but keeping my content as I have a lot of posts. How do I achieve this? Lastly, how do I populate now that manage.py has been phased out, if I dont use docker? Thanks.

**Comment by rochacbruno** [comment]
@eurabilis the structure might be changed, only with changes packed by 3rd part extensions such as Flask-Security.

Just run `$ manage populate` manage.py file has been replaces with `manage` a command line tool.

**Comment by eurabilis** [comment]
@rochacbruno thanks! I googled the command out, but it took a while because I kept getting links to the old reference. So what's the best way to update just the changed and needed schemas, leaving my content and users, configuration settings etc. I have been messing with .json files and importing them with a program, but I don't know the .json language well so I'm using the help of a validator. Is there a better way than to update like this manually?  as you can see http://www.minecraftmafia.co I love quokka and use it exclusively. I want to always run the latest version but doing that whilst keeping my changes is a nightmare. PS: I appreciate and respect everyones hard work here. Thanks

**Comment by eurabilis** [comment]
Closing this as my question was answered.
