### ISSUE TITLE
Demo Server down

### ISSUE THREAD

**Issue by atlasloewenherz** [quokkaproject/quokka#407]
please check the demo server availibility!

`

> HTTP/1.1 500 Internal Server Error
> Date: Mon, 24 Oct 2016 09:54:23 GMT
> Server: Apache/2.2.15 (Red Hat)
> Content-Type: text/html; charset=iso-8859-1
> Content-Length: 623
> Accept-Ranges: none
> Connection: keep-alive

`

thanks
Yassine

**Comment by marcosptf** [comment]
https://github.com/quokkaproject/quokka/issues/386

**Comment by OmniaGit** [comment]
the server is down ...

**Comment by ghost** [comment]
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Apache/2.2.15 (Red Hat) Server at demo.quokkaproject.org Port 80
