### ISSUE TITLE
Module template_folder not working as expected

### ISSUE THREAD

**Issue by yeradis** [quokkaproject/quokka#41]
I know that the blueprint template folder is added to the searchpath of templates but with a lower priority than the actual application’s template folder. 

In that way, current post module , has a post folder under templates module to avoid this.

But is not working, also, i just tried to give a unique name(Jinja by default caches a template based on its name) to each module template, without success.

Also remove the template_folder module property and placed the templates under app main templates, without any success.

The only templates that are applied are those under themes.

is this the expected behavoir ?

How is it supposed to work ? 

Themes are not supposed to know about modules stuff or they must ?

**Comment by rochacbruno** [comment]
The idea is to work with themes, but with fallback to defaut templates in /templates folder. I will take a look on this , if needed I will change the way templates are being loaded.

Any help or suggestion is appreciated.

Tks

**Comment by rochacbruno** [comment]
I changed the way quokka_themes loads the templates, now the behavior is:
1. Always try to find the template inside themes/**theme_name**/**template_path**  
   if not found, then:
2. Try to load the template from app quokka/templates/**template_path**  
   if not found then:  
3. Try to load the template from blueprint/**template_folder**/**template_path** (default flask behavior)  
   if not found then:  
4. raise TemplateNotFound exception.  

Also I changed the way render_template works. Now you can pass only one template_path:
`return render_template("template_path/template.html")`

Or you can pass a list of templates to try:  
`return render_template(["path1.html", "path2.html"])`

Also in default content views it will add automatically the templates "content/**object_class_name_**detail.html" and "content/**object_class_name_**list.html" as the high priority templates.

So in example for quokka-commerce: ['content/commerce_product_detail.html', ....]  

The **object_class_name** is **modulename**_**modelname**  

In that way if the module needs to use a customized template it can do by the above method or creating a custom view for the module and registering a specific url.

**OBS**: All the text above need to go to the wiki.

**Comment by rochacbruno** [comment]
Template loading order to include in wiki

1  content/
2      contentlongslug.html
3 
4      appname/channellongslug__modelname_suffix.html
5                    *_recursiveuntilroot_modelname_suffix.html
6      appname/channellongslug_suffix.html
7                    *_recursiveuntilroot_suffix.html
8      appname/modelname_suffix.html
9      appname/suffix.html
10 
11     channellongslug_modelname_suffix.html
12     *_recursiveuntilroot_modelname_suffix.html
13     channellongslug_suffix.html
14     *_recursiveuntilroot_suffix.html
15 
16     modelname_suffix.html

Try the above in /themes/ and also in /templates/

at last try to load.

18     suffix.html
