### ISSUE TITLE
Documentation points to former Git repository (rochabruno instead of pythonhub)

### ISSUE THREAD

**Issue by rturk** [quokkaproject/quokka#43]
Install tutorial documentation points to:
(quokka-env)~/quokka-env$ git clone https://github.com/rochacbruno/quokka

as the source for install,

Isn't the correct source at: pythonhub?
(quokka-env)~/quokka-env$ git clone https://github.com/pythonhub/quokka

**Comment by gtcarvalh0** [comment]
It also works that way @rturk

**Comment by rochacbruno** [comment]
@gtsalles is right but I will fix.

**Comment by rochacbruno** [comment]
https://github.com/pythonhub/quokka/commit/e46b51fdfa46ff51459768b651caec3ee61820bf
