### ISSUE TITLE
Add Howto support Nginx + uWSGI

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#47]
Add support howto:

Configure Nginx + uWSGI or Gunicorn

**Comment by jniltinho** [comment]
Install Quokka + Nginx + uWSGI OpenSUSE 11.X 12.X 13.X:

https://gist.github.com/jniltinho/6998822

**Comment by jniltinho** [comment]
Support Ubuntu

Install Quokka + Nginx + uWSGI Ubuntu:

https://gist.github.com/jniltinho/6999857

**Comment by rochacbruno** [comment]
:+1:

**Comment by ellisonleao** [comment]
:+1:
