### ISSUE TITLE
per channel/content access control

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#48]
Implement a general model **AccessControl** with roles_accepted definition for read/edit/list/delete

This will be applied for Channel and Content

This should have a default **api** method to check the permission

The generic views and api should call this method to define if access is allowed.

The admin should query the fields to define the access control.

**Comment by lboaretto** [comment]
Cool! :+1: 

read[own]/edit[own]/list[own]/delete[own] looks great!

**Comment by rochacbruno** [comment]
related to #221
