### ISSUE TITLE
Admin Dashboard Custom Views

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#49]
Admin Dashboard Like:

http://bootstrapmaster.com/live/simpliq2/
Cool

**Comment by rochacbruno** [comment]
:+1:  it can be implemented in IndexView

**Comment by jniltinho** [comment]
changes which file?

**Comment by rochacbruno** [comment]
The view: https://github.com/pythonhub/quokka/blob/master/quokka/core/admin/views.py
The template: https://github.com/pythonhub/quokka/blob/master/quokka/templates/admin/index.html

**Comment by guswidrig** [comment]
Is that a free or payed template?

**Comment by jniltinho** [comment]
Payed

**Comment by rochacbruno** [comment]
Implemented this -> https://github.com/pythonhub/quokka/wiki/custom-views-on-admin Now it will be easy to set a dashboard as the index page. look at the example screenshot
