### ISSUE TITLE
'media' folder doesn't exist

### ISSUE THREAD

**Issue by kevinbowrin** [quokkaproject/quokka#5]
Media folder is referenced, but does not exist.

**Comment by kevinbowrin** [comment]
/quokka/quokka/templates
/quokka/quokka/static
_/quokka/quokka/media_

**Comment by rochacbruno** [comment]
It is on gitignore, because I do not wanted to push my local media files. https://github.com/rochacbruno/quokka/blob/master/.gitignore#L35

I will solve that removing /media from admin filemanager

Thanks again
