### ISSUE TITLE
change internal comment system to a modular/detached/async

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#56]
Currently Comment is an embedded document, and it is the most used pattern for Mongo, but it is not easy to interchange comment system in this way.

The idea is to create a separate module **quokka-comments** detached from Content and use the same approach as Disqus, use the content identifier (can be url or id) to store comments separetelly.

also this will allow to swtich from internal commenting system to disqus, intensedebate, facebook, google comments as external plugins.

**Comment by lboaretto** [comment]
Great! :+1:

**Comment by rochacbruno** [comment]
Important: Commenting system should always use "canonical_url" as the content identifier because of the aliases. So Content should provide a property to return its canonical_url and the same for channels
