### ISSUE TITLE
Add Support Apache2 + WSGI

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#60]
Howtos:
http://bucksnort.pennington.net/blog/post/deploy-flask-mod_wsgi_virtenv/
http://flask.pocoo.org/docs/deploying/mod_wsgi/
http://stackoverflow.com/questions/11088867/trouble-running-flask-on-apache-mod-wsgi
http://stackoverflow.com/questions/17386971/hello-world-flask-apache-mod-wsgi-no-response-from-apache
http://web2py.com/book/default/chapter/13#Apache-setup
https://docs.djangoproject.com/en/1.2/howto/deployment/modwsgi/

**Comment by rochacbruno** [comment]
:+1:

**Comment by rochacbruno** [comment]
Only needs testing
