### ISSUE TITLE
Error 403 Media, media render nginx (cache)

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#63]
Com a nova configuração no Nginx:

location ~ ^/(media|static)/ {
    root    /home/quokka/quokka-env/quokka/quokka;
    expires 7d;
}

E a alteração feita para ter uma View chamada /media, não é possivel fazer o render das imagens direto no Nginx

Dessa forma não poderia ter uma pasta chamada media e uma url chamada media

Isso vai elevar todo o processo de imagem passe pelo uWSGI, não podendo assim criar pastas separadas de imagens/media em portais com grandes acessos.

**Comment by jniltinho** [comment]
Uma sugestão é trocar o nome da pasta de media para _media

**Comment by rochacbruno** [comment]
Fix! folder name changed to mediafiles
