### ISSUE TITLE
Content editor widget

### ISSUE THREAD

**Issue by guswidrig** [quokkaproject/quokka#64]
Currently the tinymce implementation is being done at template level, I suggest to create a **ContentEditor** with interchangeable support for various formats as html, markdown, creole and rst

**Comment by lovesh** [comment]
Even i feel the editor support is limited. I cant change fonts, and when i paste some code snipplet it removes the indentation on its own.

**Comment by rochacbruno** [comment]
Implemented as a widget https://github.com/pythonhub/quokka/blob/master/quokka/core/widgets.py#L7

So tinymce can be configured in https://github.com/pythonhub/quokka/blob/master/quokka/themes/cosmo/templates/admin/texteditor/tinymce.html

Any other editor can be implemented simply creating a new template "aloha.html" or something else, than passing it to the widget.
