### ISSUE TITLE
Info about static files

### ISSUE THREAD

**Issue by Bernardoow** [quokkaproject/quokka#653]
Hi @rochacbruno 

How do you deliver correct static files? Ex Theme A or Theme B.

**Comment by rochacbruno** [comment]
Hi,

There is this view https://github.com/rochacbruno/quokka/blob/master/quokka/core/themes.py#L33

when requesting `/theme/....` it will always get the folder which is the active theme.

When deploying lets say on `nginx` the better woul be to map the `/theme' directly to the theme folder.

**Comment by Bernardoow** [comment]
Ok. Thanks for this information.
