### ISSUE TITLE
Logout Action in Admin

### ISSUE THREAD

**Issue by Bernardoow** [quokkaproject/quokka#654]
Hi,

It's possible add logout action in admin page?

I need register view like this?
`    app.admin.register(
        app.db.index,
        AdminPagesView,
        name='Pages',
        endpoint='pageview'
    )`

**Comment by rochacbruno** [comment]
Hi @Bernardoow it is easy to add the logout there, no need to register. The `/logout` route already exists so we only need to add it to the template.

I know in the flask-admin base template there is a `{block}` to add auth links, so we need to figure out exacly which template is and then put the file with the proper block in https://github.com/rochacbruno/quokka/tree/master/quokka/templates/admin

**Comment by Bernardoow** [comment]
It's here [Place to add itens near a CMS menu](https://github.com/rochacbruno/quokka/blob/9051a57694ad4807c08bba7d9643e9dbda827aa4/quokka/core/content/__init__.py#L10)

I tried adding but I did not succeed. I have no knowledge in flask admin. = /


I thought about doing this.
![image](https://user-images.githubusercontent.com/4077212/36917171-dead99d4-1e34-11e8-85f2-0a9709bfe68d.png)

**Comment by rochacbruno** [comment]
@Bernardoow I'll work on this
