### ISSUE TITLE
Create Home To quokaproject.org

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#66]
Create Home To quokaproject.org

Like: http://gitlab.org/

Using:
http://foundation.zurb.com/
http://www.getuikit.com/
http://bootswatch.com/cosmo/
http://metroui.org.ua/
https://wrapbootstrap.com/themes/landing-pages
ia-no.1-metro-bootstrap-theme-WB07F9G8L
http://codecanyon.net/item/metro-help-desk-support-tickets/full_screen_preview/3281394
http://codecanyon.net/item/melonhtml5-metro-ui/2986068?ref=sdeering

**Comment by rochacbruno** [comment]
I like the bootswatch cosmo theme! I think I will switch default admin theme to this.

also here is a simple landing page: https://pkghub.io/

**Comment by jniltinho** [comment]
:+1:  -> bootswatch cosmo theme! Cool

**Comment by jniltinho** [comment]
bootswatch cosmo theme, using Bootstrap 3.0 
Flask-Admin -> Bootstrap 2.3

**Comment by jniltinho** [comment]
:+1:  -> http://pythonhub.github.io/quokka/

**Comment by rochacbruno** [comment]
:+1: now, how to set a custom domain?

**Comment by jniltinho** [comment]
Howto https://help.github.com/articles/setting-up-a-custom-domain-with-pages

Create repo pythonhub.github.io

https://github.com/pythonhub/pythonhub.github.io

In master repo
Create CNAME file, create files html

CNAME
www.quokkaproject.org

Create Pages:

Change DNS:

www.quokkaproject.org    IN CNAME      pythonhub.github.io.

Migrate Repo ? 
https://github.com/pythonhub/quokka -> https://github.com/quokka/quokka

quokka.github.io -> www.quokkaproject.org or quokkaproject.org

**Comment by jniltinho** [comment]
Like: -> https://github.com/jniltinho/jniltinho.github.io

jniltinho.github.io redirect to home.linuxpro.com.br

**Comment by jniltinho** [comment]
Fix 
New Home page to Project -> http://quokkaproject.org, created landing page Boostrap 3 Theme Cosmo.

http://getbootstrap.com/
http://bootswatch.com/cosmo/

Social Likes
http://fgte.st/SocialCount/examples/index.html
https://github.com/filamentgroup/SocialCount/
