### ISSUE TITLE
Get settings from generic env vars started by QUOKKA_

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#68]
Every ENV variable started with QUOKKA_ should turn to settings value, format is also specified in the env name.

``` bash
export QUOKKA_STR_DEFAULT_THEME = "blank"
```

will become in settings

```
DEFAULT_THEME = "blank"
```

``` bash
export QUOKKA_INT_PAGINATION = "10"
```

to

```
PAGINATION = 10
```

``` bash
export QUOKKA_DICT_MONGODB_SETTINGS = '{"DB": "my_db"}'
```

to

```
MONGODB_SETTINGS = {'DB': 'my_db'}
```

Those variables should override .settings or .localsettings

for tests, only of vars starts with QUOKKATEST_

Any ideas?

**Comment by ellisonleao** [comment]
i think we can get this vars on flask app dict config using os.environ , right?  That's a nice addon. :+1:

**Comment by rochacbruno** [comment]
Reading one by one is painful, so I changed to the default Flask config handler. 

setting

``` bash
export QUOKKA_SETTINGS=/path/settings.cfg
```

and having **/path/settings.cfg** with pure Python syntax

``` python
DEFAULT_THEME = "blank"
MONGODB_SETTINGS = {"DB": "MY_DB"}
...
...
```

all UPPER case.

So any var in there will overrride app settings..

For tests use

``` bash
export QUOKKATEST_SETTINGS=/path/test_settings.cfg
```
