### ISSUE TITLE
Error upload image Content -> Image

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#69]
Admin -> Content -> Image

Error:
Failed to create model. decoder jpeg not available

**Comment by rochacbruno** [comment]
https://github.com/pythonhub/quokka/wiki/Troubleshooting

**Comment by jniltinho** [comment]
Add Wiki Support OpenSUSE

**Comment by jniltinho** [comment]
Add Ubuntu:

sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/
sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/
sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/

http://www.sandersnewmedia.com/why/2012/04/16/installing-pil-virtualenv-ubuntu-1204-precise-pangolin/

**Comment by jniltinho** [comment]
Fix Ubuntu 12.04 32Bits :+1:

**Comment by jniltinho** [comment]
Add script autoinstall

**Comment by jniltinho** [comment]
Update Wiki, Fix OpenSUSE.

Update Script, after.
