### ISSUE TITLE
Create Flask-Admin theme based in zurb foundation.

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#7]
Bootstrap is good but Foundation is better in responsiveness and it is clean, better for customization.

Create a default theme for Flask-admin based in zurb.foundation.

**Comment by jonasteuwen** [comment]
I have most of it working on my local copy with a plain port of it do the default quokka theme. Will report back when done.

**Comment by rochacbruno** [comment]
:+1:

**Comment by jonasteuwen** [comment]
(Still working on it, busy at work. The javascript was still quite buggy.)

**Comment by guswidrig** [comment]
I am also trying to implement Foundation theme, now Quokka added support for themes in admin, so it can be done in themes/default/admin folder and also in themes/default/static.

I'll create a separate repo for this.

**Comment by jniltinho** [comment]
:+1:

**Comment by rochacbruno** [comment]
Implemented COSMO template, so this is one is now invalid.
