### ISSUE TITLE
Add support Gist Tag

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#80]
Add support Gist Tag
Like -> http://octopress.org/docs/plugins/gist-tag/

**Comment by ellisonleao** [comment]
We can use Flask-Gist : https://github.com/ellisonleao/Flask-Gist

**Comment by DiegoYungh** [comment]
easy and functional :+1:

**Comment by rochacbruno** [comment]
Should be a plugin for #231 summernote.org
