### ISSUE TITLE
Responsive design rendering issue

### ISSUE THREAD

**Issue by akaRem** [quokkaproject/quokka#82]
Renders like sh*t.

logged in as admin
http://demo.quokkaproject.org/admin/contentview/

![2013-11-09 23 19 07](https://f.cloud.github.com/assets/1472728/1507300/dd469694-4973-11e3-8714-e3d6a499d8c1.png)

**Comment by rochacbruno** [comment]
This problem is up to Flask-Admin. 
So we need to try to fix this issue in Flask-Admin and maybe open an issue there.
It should use a responsive table plugin.

**Comment by rochacbruno** [comment]
@akaRem  being fixed in Flask-Admin https://github.com/flask-admin/flask-admin/pull/1017
