### ISSUE TITLE
Multiple UI issues&mistakes in admin view

### ISSUE THREAD

**Issue by akaRem** [quokkaproject/quokka#83]
logged in as admin
http://demo.quokkaproject.org/admin/contentview/new/

"Available Until" shall indicate when available forever; blank line means never available, as I suppose (and It's not true as i suppose).
"Created At" shall not be editable.
"Updated At" shall not be editable in "Create" mode (and must be equal to "Created At").
"Created By" shall not be editable or at least current user shall be selected by default.
"Last Updated By" - the same as for "Updated At", "Created By". BTW, "Last" is odd.

Also, order is incorrect, the correct one is: "Created At", "Created By", "Updated At", "Updated By"

"Published" checkbox shall be renamed to "Publish". Content can't have state "published" until it is added.

"Mpath" is not obvious field name (I really can't guess what does it mean).

When "Tags" is clicked, the "x" sign is too far from input (and on wide screen it is too hard to say to which field it is dedicated). They also need autocomplete or at least help text "write by comma in square brackets" or something else.
"Values" is not obvious name (even when clicked and sub-form is shown). When sub-form is shown, the "x" sign stands in one line with "Values">"Name", but deletes values block, not name field.

Every field is very small. Fields could be stretchable (why not?).
The most of the fields really need help text.

What difference between "Submit" and "Save and Add"? It looks like it is the same button, but copied with different names. Why are they SO BIG!?

"Available At", "Last Updated By", "Show On Channel" etc are not headings. So they shall be written as "Available at", "Last updated by", "Show on channel" etc

Tab order is broken: checkboxes and buttons are not accessible at all.
(main menu is also inaccessible by Tab button)

---

I'm not a native speaker, sorry for my English: it's not offensive - it's how I can..

**Comment by rochacbruno** [comment]
Hi, Thanks for testing Quokka and pointing those mistakes.

I am now working on admin views and I will take your considerations.

Tks.

**Comment by akaRem** [comment]
Good!
I hope that it was helpful.

**Comment by rochacbruno** [comment]
It was!

I changed a lot of things in admin, "Content" item has gone, now you have only "Post", "Image' etc.. I fixed some issues on admin views and created some better widgets.

Tks!
