### ISSUE TITLE
create a command to create/update mongo indexes

### ISSUE THREAD

**Issue by rturk** [quokkaproject/quokka#86]
I'm not sure if MongoEngine supports automatically creating indexes for EmbeddedDocuments in https://github.com/pythonhub/quokka/blob/master/quokka/core/models.py

Example:  Class Comment has a meta class that does not produces any result on the main Content Class

class Comment(db.EmbeddedDocument): 
(...)
   meta = {
        'indexes': ['-created_at', '-available_at'],
        'ordering': ['-created_at']
    }

class Content(HasCustomValue, Publishable, LongSlugged, Commentable)
(...)  
    meta = {
        'allow_inheritance': True,
        'indexes': ['-created_at', 'slug'],
        'ordering': ['-created_at']
    }

Creates only two indexes, 'created_at and slug

**Comment by rochacbruno** [comment]
Yeah you are right, to endure indexes it need to be defined in the parent document, I will try to put this in a separate method, so have a commad "python manage.py ensure_indexes"

**Comment by rturk** [comment]
Or maybe upgrade how MongoEngine handles embedded documents indexes, certainly a more robust solution.
