### ISSUE TITLE
Allow to set editor dinamically

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#87]
https://github.com/pythonhub/quokka/blob/master/quokka/themes/cosmo/templates/admin/texteditor/tinymce.html

https://github.com/pythonhub/quokka/blob/master/quokka/core/widgets.py#L7

Editor should be set dinamically in admin, out of the box for tinymce, redactor and some markdown editor.

**Comment by lovesh** [comment]
I would like to have this feature too

**Comment by rochacbruno** [comment]
Implemented! Now it is possible to swtich between html and markdown by changing a select dropdown.
