### ISSUE TITLE
Cant access to admin page

### ISSUE THREAD

**Issue by delegans** [quokkaproject/quokka#90]
Just install quokka from git and setup it as described. The home page works correctly. But when I go to the url "/admin" the server response RuntimeError: Could not find the active theme. What could be the cause? Thx!

**Comment by rochacbruno** [comment]
Sorry, this is a problem with the security version.

Please try entering in your virtualenv and do:

pip uninstall flak-security
Y

pip install http://github.com/pythonhub/flask-security/tarball/develop

It will install a forked version of flask swcurity which has theming support.

**Comment by rochacbruno** [comment]
I changed the install order, I guess it fix the problem, tested here and worked ok.

**Comment by delegans** [comment]
The problem is fixed. Thanks!
