### ISSUE TITLE
In place edit for posts

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#92]
If "admin" or "editor" is logged in, should see an "EDIT" icon on the top of each post, it should open a "modal" window with quick-edit form to edit Title, Slug, Body/Description and tags.

The modal should follow the "content_format" to choose the editor.

**Comment by jonasteuwen** [comment]
How about things like Aloha editor?

**Comment by rochacbruno** [comment]
@jonasteuwen I like aloha, I had many problems to install it, conflicts with bootstrap...

It would be nice as a front-end editor http://www.aloha-editor.org/demos/3col/

Should find some thing like this to edit markdown, so we fix with tinymce + lepture for admin and aloha + **something for markdown** for front-end editing.

front-end editing is dependent on the theme, so we can write some patterns for designers to follow, but its optional for the theme to support the inline editing.

**Comment by rochacbruno** [comment]
http://hallojs.org/demo/markdown/

**Comment by rochacbruno** [comment]
https://github.com/fguillen/MDMagick

**Comment by rochacbruno** [comment]
http://createjs.org/

**Comment by rochacbruno** [comment]
Will be done with #231
