### ISSUE TITLE
Amendment to install docs

### ISSUE THREAD

**Issue by pixiemars** [quokkaproject/quokka#94]
Hiya

I noticed while installing that my new dev vm threw up an error while compiling the PIL imaging extension. It might be good to put a reminder in the install notes to make sure python-dev is installed.

sudo apt-get install python-dev

Mike

**Comment by ellisonleao** [comment]
:+1:

**Comment by rochacbruno** [comment]
:+1:  There is a trouble shooting page in wiki https://github.com/pythonhub/quokka/wiki/Troubleshooting, I will include this in the installation instruction and also on that wiki page.

**Comment by rochacbruno** [comment]
BTW, @pixiemars what distribution did you run? ubuntu?

**Comment by pixiemars** [comment]
Cool cheers @Bruno.

Yeah the install was on Ubuntu 12.10

**Comment by rochacbruno** [comment]
Done: https://github.com/pythonhub/quokka/wiki/Installation#on-a-ubuntudebiancentosopensuse-shell-do 

Tks.

**Comment by pixiemars** [comment]
Awesome! You guys rock.
