### ISSUE TITLE
Relase PyPi package and change the core architecture

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#97]

**Comment by rochacbruno** [comment]
## Draft

Quokka should be installed via pip

`pip install quokka`

From the current repo, themes, mediafiles, staticfiles, manage, run, wsg will be removed. 

The "quokka" package should only contain the core and the base modules.

Once installed user should do

``` bash
quokka startproject project_name
```

So using CookieCutter it will ask some things and create the following tree.

``` bash
project_name
|__ mediafiles/
|__ themes/
    |__ default/
    |__ admin/
|__ static/
|__ __init__.py
|__ app.py
|__ wsgi.py
|__ manage.py
|__ local_settings.py
```

So **app.py** will instantiate the **Quokka** application and expose this.

### The modules

Modules should be also installed via PyPI

`pip install quokka-cart`

So Quokka should use the same way Flask threat extensions but with a module namespace.

``` python
from quokka.modules.cart import Cart, Product
```

Once installed, modules will be available in the CMS, only need to activate it via settings or via admin.

**Comment by ellisonleao** [comment]
The actual modules implemented on quokka will become core models (Post, Accounts, etc) ?

**Comment by rochacbruno** [comment]
the core modules posts, media and accounts will not change, they will be in quokka/modules folder.

But, in `modules/__init__.py` we will do the same hack that Flask does with .ext allowing `form quokka.modules.*` to import packages from dist-packages.

**Comment by ellisonleao** [comment]
nice. :+1:

**Comment by avelino** [comment]
If add the core CMS at PyPI and make project to generate a project?

**Comment by rochacbruno** [comment]
#229
